/*
 * Manuale 5.5 — dati locali (fonte di verità del repo).
 * Riassunti originali in italiano, verificati sul PDF ufficiale del
 * Player's Handbook 2024 — NON testo integrale (copyright).
 *
 * Struttura pensata per l'app multi-personaggio:
 * - spells:  incantesimi condivisi, ogni voce ha i tag `classes`
 * - classes: tratti base + tabelle di progressione (indice = livello, 0 inutilizzato)
 * - species: specie con i tratti riassunti
 * - slotTables: progressioni slot condivise (full/half caster, patto warlock)
 *
 * cloud.js carica tutto su Firestore (manuals/5.5/{spells|classes|species})
 * quando `version` locale è più nuova di quella remota.
 */
window.MANUAL_55 = {
  version: 6,

  slotTables: {
    /* slot per livello di classe: array di slot per livello incantesimo 1..9 */
    full: [null,
      [2], [3], [4, 2], [4, 3], [4, 3, 2], [4, 3, 3], [4, 3, 3, 1], [4, 3, 3, 2],
      [4, 3, 3, 3, 1], [4, 3, 3, 3, 2], [4, 3, 3, 3, 2, 1], [4, 3, 3, 3, 2, 1],
      [4, 3, 3, 3, 2, 1, 1], [4, 3, 3, 3, 2, 1, 1], [4, 3, 3, 3, 2, 1, 1, 1],
      [4, 3, 3, 3, 2, 1, 1, 1], [4, 3, 3, 3, 2, 1, 1, 1, 1], [4, 3, 3, 3, 3, 1, 1, 1, 1],
      [4, 3, 3, 3, 3, 2, 1, 1, 1], [4, 3, 3, 3, 3, 2, 2, 1, 1]],
    half: [null,
      [2], [2], [3], [3], [4, 2], [4, 2], [4, 3], [4, 3],
      [4, 3, 2], [4, 3, 2], [4, 3, 3], [4, 3, 3],
      [4, 3, 3, 1], [4, 3, 3, 1], [4, 3, 3, 2], [4, 3, 3, 2],
      [4, 3, 3, 3, 1], [4, 3, 3, 3, 1], [4, 3, 3, 3, 2], [4, 3, 3, 3, 2]],
    /* warlock: numero di slot di patto e loro livello */
    pactSlots: [0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4],
    pactSlotLevel: [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
  },

  classes: {
    barbaro: {
      name: 'Barbaro', hitDie: 'd12', primaryAbility: 'FOR', saves: ['FOR', 'COS'],
      casterType: 'none',
      rages: [0, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6],
      rageDamage: [0, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4],
      weaponMastery: [0, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
    },
    bardo: {
      name: 'Bardo', hitDie: 'd8', primaryAbility: 'CAR', saves: ['DES', 'CAR'],
      casterType: 'full', spellAbility: 'CAR',
      bardicDie: [null, 'd6', 'd6', 'd6', 'd6', 'd8', 'd8', 'd8', 'd8', 'd8', 'd10', 'd10', 'd10', 'd10', 'd10', 'd12', 'd12', 'd12', 'd12', 'd12', 'd12'],
      cantripsByLevel: [0, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
      preparedByLevel: [0, 4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 16, 16, 17, 17, 18, 18, 19, 20, 21, 22],
      slotLevelByLevel: [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 9, 9]
    },
    chierico: {
      name: 'Chierico', hitDie: 'd8', primaryAbility: 'SAG', saves: ['SAG', 'CAR'],
      casterType: 'full', spellAbility: 'SAG',
      channelDivinity: [0, 0, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4],
      cantripsByLevel: [0, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
      preparedByLevel: [0, 4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 16, 16, 17, 17, 18, 18, 19, 20, 21, 22],
      slotLevelByLevel: [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 9, 9]
    },
    druido: {
      name: 'Druido', hitDie: 'd8', primaryAbility: 'SAG', saves: ['INT', 'SAG'],
      casterType: 'full', spellAbility: 'SAG',
      wildShape: [0, 0, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4],
      cantripsByLevel: [0, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
      preparedByLevel: [0, 4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 16, 16, 17, 17, 18, 18, 19, 20, 21, 22],
      slotLevelByLevel: [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 9, 9]
    },
    guerriero: {
      name: 'Guerriero', hitDie: 'd10', primaryAbility: 'FOR o DES', saves: ['FOR', 'COS'],
      casterType: 'none',
      secondWind: [0, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
      weaponMastery: [0, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6]
    },
    ladro: {
      name: 'Ladro', hitDie: 'd8', primaryAbility: 'DES', saves: ['DES', 'INT'],
      casterType: 'none',
      sneakAttackD6: [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10]
    },
    mago: {
      name: 'Mago', hitDie: 'd6', primaryAbility: 'INT', saves: ['INT', 'SAG'],
      casterType: 'full', spellAbility: 'INT',
      cantripsByLevel: [0, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
      preparedByLevel: [0, 4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 16, 16, 17, 18, 19, 21, 22, 23, 24, 25],
      slotLevelByLevel: [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 9, 9]
    },
    monaco: {
      name: 'Monaco', hitDie: 'd8', primaryAbility: 'DES e SAG', saves: ['FOR', 'DES'],
      casterType: 'none',
      martialArtsDie: [null, 'd6', 'd6', 'd6', 'd6', 'd8', 'd8', 'd8', 'd8', 'd8', 'd8', 'd10', 'd10', 'd10', 'd10', 'd10', 'd10', 'd12', 'd12', 'd12', 'd12'],
      focusPoints: [0, 0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
      unarmoredMovementM: [0, 0, 3, 3, 3, 3, 4.5, 4.5, 4.5, 4.5, 6, 6, 6, 6, 7.5, 7.5, 7.5, 7.5, 9, 9, 9]
    },
    paladino: {
      name: 'Paladino', hitDie: 'd10', primaryAbility: 'FOR e CAR', saves: ['SAG', 'CAR'],
      casterType: 'half', spellAbility: 'CAR',
      channelDivinity: [0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
      preparedByLevel: [0, 2, 3, 4, 5, 6, 6, 7, 7, 9, 9, 10, 10, 11, 11, 12, 12, 14, 14, 15, 15],
      slotLevelByLevel: [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5]
    },
    ranger: {
      name: 'Ranger', hitDie: 'd10', primaryAbility: 'DES e SAG', saves: ['FOR', 'DES'],
      casterType: 'half', spellAbility: 'SAG',
      favoredEnemy: [0, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6],
      preparedByLevel: [0, 2, 3, 4, 5, 6, 6, 7, 7, 9, 9, 10, 10, 11, 11, 12, 12, 14, 14, 15, 15],
      slotLevelByLevel: [0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5]
    },
    stregone: {
      name: 'Stregone', hitDie: 'd6', primaryAbility: 'CAR', saves: ['COS', 'CAR'],
      casterType: 'full', spellAbility: 'CAR',
      sorceryPoints: [0, 0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
      cantripsByLevel: [0, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
      preparedByLevel: [0, 2, 4, 6, 7, 9, 10, 11, 12, 14, 15, 16, 16, 17, 17, 18, 18, 19, 20, 21, 22],
      slotLevelByLevel: [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 9, 9]
    },
    warlock: {
      name: 'Warlock', hitDie: 'd8', primaryAbility: 'CAR', saves: ['SAG', 'CAR'],
      casterType: 'pact', spellAbility: 'CAR',
      invocations: [0, 1, 3, 3, 3, 5, 5, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10, 10],
      cantripsByLevel: [0, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
      preparedByLevel: [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15],
      slotLevelByLevel: [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
    }
  },

  species: {
    aasimar: {
      name: 'Aasimar', size: 'Media o Piccola', speedM: 9,
      traits: [
        { name: 'Resistenza Celestiale', desc: 'Resistenza ai danni necrotici e radiosi.' },
        { name: 'Scurovisione', desc: '18 metri.' },
        { name: 'Mani Guaritrici', desc: 'Azione Magica: una creatura toccata recupera un numero di d4 pari al tuo bonus di competenza. 1/riposo lungo.' },
        { name: 'Portatore di Luce', desc: 'Conosci il trucchetto Luce (Carisma come caratteristica).' },
        { name: 'Rivelazione Celestiale', desc: 'Dal livello 3, azione bonus: trasformazione per 1 minuto (1/riposo lungo) a scelta tra Ali Celesti (volo pari alla velocità), Radiosità Interiore (luce e danni radiosi pari al bonus di competenza a chi è entro 3 m) o Sudario Necrotico (TS Carisma o Spaventato). 1 volta per turno infliggi danni extra pari al bonus di competenza.' }
      ]
    },
    dragonide: {
      name: 'Dragonide', size: 'Media', speedM: 9,
      traits: [
        { name: 'Ascendenza Draconica', desc: 'Scegli il drago progenitore: determina il tipo di danno di soffio e resistenza (es. Oro = fuoco).' },
        { name: 'Soffio', desc: 'Sostituisce un attacco dell\'azione Attacco: cono di 4,5 m o linea di 9 m; TS Destrezza (CD 8 + mod. Cos + bonus competenza), 1d10 danni del tipo dell\'ascendenza (2d10 al livello 5, 3d10 all\'11, 4d10 al 17), dimezzati se superato. Usi pari al bonus di competenza per riposo lungo.' },
        { name: 'Resistenza al Danno', desc: 'Resistenza al tipo di danno della tua ascendenza.' },
        { name: 'Scurovisione', desc: '18 metri.' },
        { name: 'Volo Draconico', desc: 'Dal livello 5, azione bonus: ali spettrali per 10 minuti, velocità di volo pari alla velocità. 1/riposo lungo.' }
      ]
    },
    elfo: {
      name: 'Elfo', size: 'Media', speedM: 9,
      traits: [
        { name: 'Scurovisione', desc: '18 metri.' },
        { name: 'Retaggio Elfico', desc: 'Scegli Drow (Luci Danzanti; scurovisione 36 m), Elfo Alto (Prestidigitazione, sostituibile a ogni riposo lungo) o Elfo dei Boschi (velocità 10,5 m; Druidismo). Ai livelli 3 e 5 impari un incantesimo sempre preparato, con 1 lancio gratis per riposo lungo.' },
        { name: 'Ascendenza Fatata', desc: 'Vantaggio ai TS per evitare o terminare Affascinato.' },
        { name: 'Sensi Acuti', desc: 'Competenza in Intuizione, Percezione o Sopravvivenza.' },
        { name: 'Trance', desc: 'Non dormi e la magia non può addormentarti; riposo lungo in 4 ore di meditazione.' }
      ]
    },
    gnomo: {
      name: 'Gnomo', size: 'Piccola', speedM: 9,
      traits: [
        { name: 'Scurovisione', desc: '18 metri.' },
        { name: 'Astuzia Gnomesca', desc: 'Vantaggio ai TS di Intelligenza, Saggezza e Carisma.' },
        { name: 'Retaggio Gnomesco', desc: 'Gnomo dei Boschi: Illusione Minore e Parlare con gli Animali sempre preparato (lanci gratis pari al bonus di competenza per riposo lungo). Gnomo delle Rocce: Riparare e Prestidigitazione, con cui crei piccoli congegni a orologeria (max 3).' }
      ]
    },
    goliath: {
      name: 'Goliath', size: 'Media (2,1–2,4 m)', speedM: 10.5,
      traits: [
        { name: 'Ascendenza dei Giganti', desc: 'Scegli un dono (usi pari al bonus di competenza per riposo lungo): Nube (teletrasporto 9 m, az. bonus), Fuoco (+1d10 fuoco a un colpo), Gelo (+1d6 freddo e −3 m di velocità), Colle (Prono a creatura Grande o inferiore colpita), Pietra (reazione: riduci il danno subito di 1d12 + mod. Cos), Tempesta (reazione: 1d8 tuono a chi ti danneggia entro 18 m).' },
        { name: 'Forma Grande', desc: 'Dal livello 5, azione bonus: diventi Grande per 10 minuti, vantaggio alle prove di Forza e +3 m di velocità. 1/riposo lungo.' },
        { name: 'Costituzione Possente', desc: 'Vantaggio ai TS per terminare Afferrato; conti come una taglia più grande per la capacità di carico.' }
      ]
    },
    halfling: {
      name: 'Halfling', size: 'Piccola', speedM: 9,
      traits: [
        { name: 'Coraggioso', desc: 'Vantaggio ai TS per evitare o terminare Spaventato.' },
        { name: 'Agilità Halfling', desc: 'Puoi muoverti nello spazio di creature di taglia superiore alla tua (senza fermartici).' },
        { name: 'Fortuna', desc: 'Quando esce 1 sul d20 di un D20 Test, ripeti il tiro e usa il nuovo risultato.' },
        { name: 'Furtività Naturale', desc: 'Puoi Nasconderti anche quando sei oscurato solo da una creatura di almeno una taglia più grande.' }
      ]
    },
    nano: {
      name: 'Nano', size: 'Media', speedM: 9,
      traits: [
        { name: 'Scurovisione', desc: '36 metri.' },
        { name: 'Resilienza Nanica', desc: 'Resistenza ai danni da veleno e vantaggio ai TS per evitare o terminare Avvelenato.' },
        { name: 'Robustezza Nanica', desc: '+1 PF massimi, e +1 di nuovo a ogni livello.' },
        { name: 'Conoscenza della Pietra', desc: 'Azione bonus: Percezione Tellurica 18 m per 10 minuti mentre sei su pietra. Usi pari al bonus di competenza per riposo lungo.' }
      ]
    },
    orco: {
      name: 'Orco', size: 'Media', speedM: 9,
      traits: [
        { name: 'Scarica di Adrenalina', desc: 'Scatto come azione bonus, con PF temporanei pari al bonus di competenza. Usi pari al bonus di competenza per riposo breve o lungo.' },
        { name: 'Scurovisione', desc: '36 metri.' },
        { name: 'Tenacia Implacabile', desc: 'Quando scendi a 0 PF senza essere ucciso sul colpo, resti invece a 1 PF. 1/riposo lungo.' }
      ]
    },
    tiefling: {
      name: 'Tiefling', size: 'Media o Piccola', speedM: 9,
      traits: [
        { name: 'Scurovisione', desc: '18 metri.' },
        { name: 'Retaggio Infernale', desc: 'Scegli Abissale, Ctonio o Infernale: un trucchetto al livello 1, poi ai livelli 3 e 5 un incantesimo sempre preparato con 1 lancio gratis per riposo lungo.' },
        { name: 'Presenza Ultraterrena', desc: 'Conosci il trucchetto Taumaturgia.' }
      ]
    },
    umano: {
      name: 'Umano', size: 'Media o Piccola', speedM: 9,
      traits: [
        { name: 'Pieno di Risorse', desc: 'Ottieni Ispirazione Eroica a ogni riposo lungo.' },
        { name: 'Abile', desc: 'Competenza in un\'abilità a scelta.' },
        { name: 'Versatile', desc: 'Un talento di Origine a scelta.' }
      ]
    }
  },

  spells: [
    /* ===== 1° livello ===== */
    { id: 'benedizione', name: 'Benedizione', level: 1, school: 'Incantamento',
      classes: ['paladino', 'chierico'],
      meta: 'Azione · 9 m · 1 min CONC · V, S, M',
      desc: 'Fino a 3 creature aggiungono 1d4 ai tiri per colpire e ai tiri salvezza finché dura. +1 bersaglio per ogni slot oltre il 1°.' },
    { id: 'comando', name: 'Comando', level: 1, school: 'Incantamento',
      classes: ['paladino', 'bardo', 'chierico'],
      meta: 'Azione · 18 m · 1 round · V',
      desc: 'Un nemico che capisca una lingua fa TS Saggezza: se fallisce esegue un comando di una parola per il suo prossimo turno. Comandi tipici: Avanzare, Cadere, Fuggi, Rannicchiati, Vieni. Niente concentrazione. +1 bersaglio per ogni slot oltre il 1°.' },
    { id: 'cura-ferite', name: 'Cura Ferite', level: 1, school: 'Abiurazione',
      classes: ['paladino', 'bardo', 'chierico', 'druido', 'ranger'],
      meta: 'Azione · Tocco · Istantaneo · V, S',
      desc: 'La creatura toccata recupera 2d8 + mod. da incantatore PF. La cura aumenta di 2d8 per ogni slot oltre il 1°.' },
    { id: 'duello-obbligato', name: 'Duello Obbligato', level: 1, school: 'Incantamento',
      classes: ['paladino'],
      meta: 'Azione bonus · 9 m · 1 min CONC · V',
      desc: 'Una creatura fa TS Saggezza: se fallisce ha svantaggio agli attacchi contro chiunque non sia te e non può allontanarsi volontariamente oltre 9 m da te. Termina se attacchi un\'altra creatura o se un tuo alleato attacca o danneggia il bersaglio.' },
    { id: 'eroismo', name: 'Eroismo', level: 1, school: 'Incantamento',
      classes: ['paladino', 'bardo'],
      meta: 'Azione · Tocco · 1 min CONC · V, S',
      desc: 'Una creatura volontaria è immune a Spaventato e all\'inizio di ogni suo turno ottiene PF temporanei pari al tuo mod. da incantatore. +1 bersaglio per ogni slot oltre il 1°.' },
    { id: 'favore-divino', name: 'Favore Divino', level: 1, school: 'Trasmutazione',
      classes: ['paladino'],
      meta: 'Azione bonus · Sé · 1 min · V, S',
      desc: 'I tuoi attacchi con arma infliggono +1d4 danni radiosi per tutta la durata. Niente concentrazione.' },
    { id: 'individuazione-bene-male', name: 'Individuazione del Bene e del Male', level: 1, school: 'Divinazione',
      classes: ['paladino', 'chierico'],
      meta: 'Azione · Sé · 10 min CONC · V, S',
      desc: 'Percepisci la presenza e la posizione di Aberrazioni, Celestiali, Elementali, Folletti, Immondi e Non Morti entro 9 m, e di luoghi consacrati o profanati.' },
    { id: 'individuazione-magico', name: 'Individuazione del Magico', level: 1, school: 'Divinazione',
      classes: ['paladino', 'bardo', 'chierico', 'druido', 'ranger', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · Sé · 10 min CONC · V, S · Rituale',
      desc: 'Percepisci la presenza di magia entro 9 m. Con un\'azione vedi l\'aura attorno a creature od oggetti magici e ne apprendi la scuola.' },
    { id: 'individuazione-veleni', name: 'Individuazione di Veleni e Malattie', level: 1, school: 'Divinazione',
      classes: ['paladino', 'chierico', 'druido', 'ranger'],
      meta: 'Azione · Sé · 10 min CONC · V, S, M · Rituale',
      desc: 'Percepisci la presenza e la posizione di veleni, creature velenose e malattie entro 9 m, e ne identifichi il tipo.' },
    { id: 'protezione-mal-bene', name: 'Protezione dal Male e dal Bene', level: 1, school: 'Abiurazione',
      classes: ['paladino', 'chierico', 'warlock', 'mago'],
      meta: 'Azione · Tocco · 10 min CONC · V, S, M (acqua santa, consumata)',
      desc: 'Una creatura volontaria è protetta da Aberrazioni, Celestiali, Elementali, Folletti, Immondi e Non Morti: questi hanno svantaggio ad attaccarla, e lei non può essere posseduta né resa Affascinata o Spaventata da loro (vantaggio ai TS se già soggetta).' },
    { id: 'punizione-ardente', name: 'Punizione Ardente', level: 1, school: 'Evocazione',
      classes: ['paladino'],
      meta: 'Azione bonus (dopo un colpo in mischia) · Sé · 1 min · V',
      desc: '+1d6 fuoco al colpo. Poi a inizio di ogni suo turno il bersaglio subisce 1d6 fuoco e fa TS Costituzione: se riesce, l\'incantesimo termina. Non richiede concentrazione. +1d6 per ogni slot oltre il 1°.' },
    { id: 'punizione-collerica', name: 'Punizione Collerica', level: 1, school: 'Negromanzia',
      classes: ['paladino'],
      meta: 'Az. bonus subito dopo aver colpito · Sé · 1 min · V',
      desc: '+1d6 necrotico al colpo. Il bersaglio fa TS Saggezza: se fallisce è Spaventato da te per tutta la durata (ripete il TS a fine di ogni suo turno). Nessuna concentrazione.' },
    { id: 'punizione-divina', name: 'Punizione Divina', level: 1, school: 'Evocazione',
      classes: ['paladino'],
      meta: 'Azione bonus (dopo un colpo in mischia) · Sé · Istantaneo · V',
      desc: 'Il bersaglio subisce 2d8 radiosi extra dal colpo; +1d8 contro Immondi e Non Morti. +1d8 per ogni slot oltre il 1°.' },
    { id: 'punizione-tonante', name: 'Punizione Tonante', level: 1, school: 'Evocazione',
      classes: ['paladino'],
      meta: 'Azione bonus (dopo un colpo in mischia) · Sé · Istantaneo · V',
      desc: '+2d6 tuono al colpo, udibile a 90 m. Il bersaglio fa TS Forza: se fallisce è spinto di 3 m e cade Prono. +1d6 per ogni slot oltre il 1°.' },
    { id: 'purificare-cibo', name: 'Purificare Cibo e Bevande', level: 1, school: 'Trasmutazione',
      classes: ['paladino', 'chierico', 'druido'],
      meta: 'Azione · 3 m · Istantaneo · V, S · Rituale',
      desc: 'Cibo e bevande non magici in una sfera di 1,5 m di raggio vengono purificati da veleni e malattie.' },
    { id: 'scudo-della-fede', name: 'Scudo della Fede', level: 1, school: 'Abiurazione',
      classes: ['paladino', 'chierico'],
      meta: 'Azione bonus · 18 m · 10 min CONC · V, S, M',
      desc: 'Una creatura a scelta entro gittata ottiene +2 alla CA per tutta la durata.' },

    /* ===== 2° livello ===== */
    { id: 'aiuto', name: 'Aiuto', level: 2, school: 'Abiurazione',
      classes: ['paladino', 'bardo', 'chierico', 'druido', 'ranger'],
      meta: 'Azione · 9 m · 8 ore · V, S, M',
      desc: 'Fino a 3 creature: i PF massimi e attuali aumentano di 5 per la durata. Con slot superiori, +5 per ogni livello oltre il 2°.' },
    { id: 'arma-magica', name: 'Arma Magica', level: 2, school: 'Trasmutazione',
      classes: ['paladino', 'ranger', 'mago'],
      meta: 'Azione bonus · Tocco · 1 ora · V, S',
      desc: 'Un\'arma non magica diventa magica con +1 ai tiri per colpire e ai danni. Niente concentrazione. Con slot di 4° o superiore il bonus diventa +2.' },
    { id: 'individuazione-oggetto', name: 'Individuazione d\'Oggetto', level: 2, school: 'Divinazione',
      classes: ['paladino', 'bardo', 'chierico', 'druido', 'ranger', 'mago'],
      meta: 'Azione · Sé · 10 min CONC · V, S, M',
      desc: 'Percepisci la direzione di un oggetto che ti è familiare entro 300 m, anche in movimento. Bloccato da uno strato di piombo.' },
    { id: 'preghiera-guarigione', name: 'Preghiera di Guarigione', level: 2, school: 'Abiurazione',
      classes: ['paladino', 'chierico'],
      meta: '10 minuti · 9 m · Istantaneo · V',
      desc: 'Fino a 5 creature recuperano 2d8 + mod. da incantatore PF e ottengono i benefici di un riposo breve. Una creatura non può beneficiarne di nuovo prima di un riposo lungo. +1d8 per ogni slot oltre il 2°.' },
    { id: 'protezione-veleno', name: 'Protezione dal Veleno', level: 2, school: 'Abiurazione',
      classes: ['paladino', 'chierico', 'druido', 'ranger'],
      meta: 'Azione · Tocco · 1 ora · V, S',
      desc: 'Neutralizzi un veleno presente nella creatura toccata. Per la durata ha vantaggio ai TS contro l\'Avvelenamento e resistenza ai danni da veleno.' },
    { id: 'punizione-radiosa', name: 'Punizione Radiosa', level: 2, school: 'Trasmutazione',
      classes: ['paladino'],
      meta: 'Azione bonus (dopo un colpo in mischia) · Sé · 1 min CONC · V',
      desc: '+2d8 radiosi al colpo. Il bersaglio emana luce intensa: tutti gli attacchi contro di esso hanno vantaggio automatico. Quando l\'incantesimo termina, il bersaglio subisce altri 2d8 radiosi. +1d8 per ogni slot oltre il 2°.' },
    { id: 'quiete-perpetua', name: 'Quiete Perpetua', level: 2, school: 'Negromanzia',
      classes: ['paladino', 'chierico', 'mago'],
      meta: 'Azione · Tocco · 10 giorni · V, S, M · Rituale',
      desc: 'Un cadavere toccato non si decompone e non può diventare Non Morto per la durata. Prolunga il tempo utile per riportarlo in vita.' },
    { id: 'ristorare-inferiore', name: 'Ristorare Inferiore', level: 2, school: 'Abiurazione',
      classes: ['paladino', 'bardo', 'chierico', 'druido', 'ranger'],
      meta: 'Azione bonus · Tocco · Istantaneo · V, S',
      desc: 'Rimuovi dalla creatura toccata una condizione tra: Accecato, Assordato, Paralizzato o Avvelenato.' },
    { id: 'trova-destriero', name: 'Trova Destriero', level: 2, school: 'Evocazione',
      classes: ['paladino'],
      meta: 'Azione · 9 m · Istantaneo · V, S',
      desc: 'Evochi un destriero ultraterreno fedele (Grande e cavalcabile). Scegli il tipo: Celestiale, Folletto o Immondo. Sostituisce un destriero precedente.' },
    { id: 'vincolo-custodia', name: 'Vincolo di Custodia', level: 2, school: 'Abiurazione',
      classes: ['paladino', 'chierico'],
      meta: 'Azione · Tocco · 1 ora · V, S, M (due anelli)',
      desc: 'Leghi una creatura volontaria a te: finché resta entro 18 m ha +1 alla CA e ai TS e resistenza a tutti i danni, ma tu subisci un ammontare di danni pari a quelli che subisce lei.' },
    { id: 'zona-di-verita', name: 'Zona di Verità', level: 2, school: 'Incantamento',
      classes: ['paladino', 'bardo', 'chierico'],
      meta: 'Azione · 18 m · 10 min · V, S',
      desc: 'Sfera di raggio 4,5 m. Chi entra o inizia il turno nell\'area fa TS Carisma: se fallisce non può mentire deliberatamente. Sai chi supera o fallisce il tiro.' },

    /* ===== 3° livello ===== */
    { id: 'arma-elementale', name: 'Arma Elementale', level: 3, school: 'Trasmutazione',
      classes: ['paladino', 'druido', 'ranger'],
      meta: 'Azione · Tocco · 1 ora CONC · V, S',
      desc: 'Un\'arma diventa magica: +1 ai tiri per colpire e +1d4 danni a scelta tra acido, freddo, fulmine, fuoco o tuono. Con slot di 5°-6°: +2 e +2d4.' },
    { id: 'aura-vitalita', name: 'Aura di Vitalità', level: 3, school: 'Abiurazione',
      classes: ['paladino', 'chierico', 'druido'],
      meta: 'Azione · Sé (aura 9 m) · 1 min CONC · V',
      desc: 'Per la durata, con un\'azione bonus una creatura a scelta nell\'aura (anche tu) recupera 2d6 PF.' },
    { id: 'cerchio-magico', name: 'Cerchio Magico', level: 3, school: 'Abiurazione',
      classes: ['paladino', 'chierico', 'warlock', 'mago'],
      meta: '1 minuto · 3 m · 1 ora · V, S, M (consumato)',
      desc: 'Cilindro di 3 m di raggio. Scegli uno o più tipi tra Celestiali, Elementali, Folletti, Immondi e Non Morti: non possono entrarci con mezzi non magici, hanno svantaggio agli attacchi contro chi sta dentro e non possono affascinare, spaventare o possedere chi è nel cerchio.' },
    { id: 'creare-cibo-acqua', name: 'Creare Cibo e Acqua', level: 3, school: 'Evocazione',
      classes: ['paladino', 'chierico'],
      meta: 'Azione · 9 m · Istantaneo · V, S',
      desc: 'Crei cibo (insipido ma nutriente) e acqua sufficienti a sfamare 15 umanoidi o 5 destrieri per 24 ore.' },
    { id: 'dissolvi-magie', name: 'Dissolvi Magie', level: 3, school: 'Abiurazione',
      classes: ['paladino', 'bardo', 'chierico', 'druido', 'ranger', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 36 m · Istantaneo · V, S',
      desc: 'Termina gli incantesimi di 3° livello o inferiore su un bersaglio a scelta. Per ogni incantesimo di livello superiore, prova di caratteristica da incantatore CD 10 + livello dell\'incantesimo.' },
    { id: 'luce-diurna', name: 'Luce Diurna', level: 3, school: 'Evocazione',
      classes: ['paladino', 'chierico', 'druido', 'ranger', 'stregone'],
      meta: 'Azione · 18 m · 1 ora · V, S',
      desc: 'Sfera di luce intensa di 18 m di raggio (+18 m di luce fioca) da un punto o un oggetto. Dissolve l\'oscurità magica creata da incantesimi di 3° o inferiore.' },
    { id: 'punizione-accecante', name: 'Punizione Accecante', level: 3, school: 'Evocazione',
      classes: ['paladino'],
      meta: 'Azione bonus (dopo un colpo in mischia) · Sé · Istantaneo · V',
      desc: '+3d8 radiosi al colpo. Il bersaglio fa TS Costituzione: se fallisce è Accecato per 1 minuto (ripete il TS a fine di ogni suo turno). +1d8 per ogni slot oltre il 3°.' },
    { id: 'rimuovere-maledizione', name: 'Rimuovere Maledizione', level: 3, school: 'Abiurazione',
      classes: ['paladino', 'chierico', 'warlock', 'mago'],
      meta: 'Azione · Tocco · Istantaneo · V, S',
      desc: 'Tutte le maledizioni sulla creatura toccata terminano. Su un oggetto maledetto, spezza il vincolo con il proprietario (la maledizione dell\'oggetto resta).' },
    { id: 'rianimare', name: 'Rianimare', level: 3, school: 'Negromanzia',
      classes: ['paladino', 'chierico', 'druido', 'ranger'],
      meta: 'Azione · Tocco · Istantaneo · V, S, M (diamanti da 300 MO, consumati)',
      desc: 'Una creatura morta da non più di 1 minuto torna in vita con 1 PF. Non funziona su chi è morto di vecchiaia e non rigenera parti del corpo mancanti.' },

    /* ===== 4° livello ===== */
    { id: 'aura-purezza', name: 'Aura di Purezza', level: 4, school: 'Abiurazione',
      classes: ['paladino', 'chierico'],
      meta: 'Azione · Sé (aura 9 m) · 10 min CONC · V',
      desc: 'Gli alleati nell\'aura non possono essere Avvelenati, hanno resistenza ai danni da veleno e vantaggio ai TS contro Accecato, Assordato, Affascinato, Paralizzato, Pietrificato, Spaventato e Stordito.' },
    { id: 'aura-vita', name: 'Aura di Vita', level: 4, school: 'Abiurazione',
      classes: ['paladino', 'chierico'],
      meta: 'Azione · Sé (aura 9 m) · 10 min CONC · V',
      desc: 'Gli alleati nell\'aura hanno resistenza ai danni necrotici e i loro PF massimi non possono essere ridotti. Chi inizia il turno nell\'aura con 0 PF recupera 1 PF.' },
    { id: 'esilio', name: 'Esilio', level: 4, school: 'Abiurazione',
      classes: ['paladino', 'chierico', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 18 m · 1 min CONC · V, S, M',
      desc: 'Il bersaglio fa TS Carisma: se fallisce è esiliato in un semipiano innocuo, Inabile. Se è nativo di un altro piano e resti concentrato per l\'intera durata, non torna. +1 bersaglio per ogni slot oltre il 4°.' },
    { id: 'individuazione-creature', name: 'Individuazione di Creature', level: 4, school: 'Divinazione',
      classes: ['paladino', 'bardo', 'chierico', 'druido', 'ranger', 'mago'],
      meta: 'Azione · Sé · 1 ora CONC · V, S',
      desc: 'Percepisci la direzione di una creatura che ti è familiare entro 300 m, anche in movimento. Bloccato dall\'acqua corrente.' },
    { id: 'interdizione-morte', name: 'Interdizione alla Morte', level: 4, school: 'Abiurazione',
      classes: ['paladino', 'chierico'],
      meta: 'Azione · Tocco · 8 ore · V, S',
      desc: 'La prima volta che il bersaglio scenderebbe a 0 PF, resta invece a 1 PF e l\'incantesimo termina. Annulla anche un effetto che ucciderebbe all\'istante senza infliggere danni.' },
    { id: 'punizione-sbalorditiva', name: 'Punizione Sbalorditiva', level: 4, school: 'Incantamento',
      classes: ['paladino'],
      meta: 'Azione bonus (dopo un colpo in mischia) · Sé · Istantaneo · V',
      desc: '+4d6 psichici al colpo. Il bersaglio fa TS Saggezza: se fallisce è Stordito fino alla fine del tuo prossimo turno. +1d6 per ogni slot oltre il 4°.' },

    /* ===== 5° livello ===== */
    { id: 'cerchio-potere', name: 'Cerchio di Potere', level: 5, school: 'Abiurazione',
      classes: ['paladino', 'chierico', 'mago'],
      meta: 'Azione · Sé (aura 9 m) · 10 min CONC · V',
      desc: 'Tu e gli alleati nell\'aura avete vantaggio ai TS contro incantesimi ed effetti magici; quando un TS riuscito dimezzerebbe il danno, lo annulla del tutto.' },
    { id: 'dissolvi-bene-male', name: 'Dissolvi il Bene e il Male', level: 5, school: 'Abiurazione',
      classes: ['paladino', 'chierico'],
      meta: 'Azione · Sé · 1 min CONC · V, S, M',
      desc: 'Celestiali, Elementali, Folletti, Immondi e Non Morti hanno svantaggio agli attacchi contro di te. Puoi terminare l\'incantesimo per interrompere una possessione (Spezzare Incantamento) o rimandare la creatura al suo piano (Congedo, TS Carisma).' },
    { id: 'evoca-celestiale', name: 'Evoca Celestiale', level: 5, school: 'Evocazione',
      classes: ['paladino', 'chierico'],
      meta: 'Azione · 27 m · 1 ora CONC · V, S, M (400 MO)',
      desc: 'Evochi uno spirito celestiale (forma di vendicatore o difensore) che agisce subito dopo di te e obbedisce ai tuoi ordini. Più potente con slot superiori.' },
    { id: 'geas', name: 'Geas', level: 5, school: 'Incantamento',
      classes: ['paladino', 'bardo', 'chierico', 'druido', 'mago'],
      meta: '1 minuto · 18 m · 30 giorni · V',
      desc: 'La creatura fa TS Saggezza: se fallisce è vincolata magicamente a un tuo comando. Subisce 5d10 psichici (max 1 volta al giorno) quando agisce in modo contrario alle tue istruzioni.' },
    { id: 'onda-distruttiva', name: 'Onda Distruttiva', level: 5, school: 'Evocazione',
      classes: ['paladino'],
      meta: 'Azione · Sé (raggio 9 m) · Istantaneo · V',
      desc: 'Energia divina esplode da te: le creature a scelta entro 9 m fanno TS Costituzione; se falliscono subiscono 5d6 tuono + 5d6 radiosi e cadono Prone (metà danni e niente Prono se superano).' },
    { id: 'punizione-esiliante', name: 'Punizione Esiliante', level: 5, school: 'Evocazione',
      classes: ['paladino'],
      meta: 'Azione bonus (dopo un colpo in mischia) · Sé · 1 min CONC · V',
      desc: '+5d10 forza al colpo. Se il colpo porta il bersaglio a meno di 50 PF, è esiliato in un semipiano innocuo (Inabile) finché ti concentri; se nativo di un altro piano, non torna.' },
    { id: 'ristorare-superiore', name: 'Ristorare Superiore', level: 5, school: 'Abiurazione',
      classes: ['paladino', 'bardo', 'chierico', 'druido', 'ranger'],
      meta: 'Azione · Tocco · Istantaneo · V, S, M (polvere di diamante da 100 MO, consumata)',
      desc: 'Riduci di 1 il livello di Indebolimento della creatura toccata, oppure termina un effetto tra: Affascinato o Pietrificato, una maledizione (incluso il vincolo con un oggetto maledetto), una riduzione dei PF massimi o di un punteggio di caratteristica.' },
    { id: 'rianimare-morti', name: 'Rianimare Morti', level: 5, school: 'Negromanzia',
      classes: ['paladino', 'bardo', 'chierico'],
      meta: '1 ora · Tocco · Istantaneo · V, S, M (diamante da 500 MO, consumato)',
      desc: 'Riporta in vita una creatura morta da non più di 10 giorni con 1 PF. L\'anima deve essere libera e disposta a tornare. Malus −4 a tiri e TS che si riduce a ogni riposo lungo.' },

    /* ===== Ranger — incantesimi propri (non condivisi col Paladino) ===== */
    /* 1° livello */
    { id: 'allarme', name: 'Allarme', level: 1, school: 'Abiurazione',
      classes: ['ranger', 'mago'],
      meta: 'Azione o Rituale · 9 m · 8 ore · V, S, M (una campanella e filo d\'argento)',
      desc: 'Imposti un allarme su una porta, una finestra o un\'area fino a 6 m di lato. Se una creatura non esclusa la tocca o vi entra, scatta un segnale a scelta: udibile (rintocco per 10 secondi entro 18 m) o mentale (ti raggiunge entro 1,6 km e ti sveglia anche se dormi).' },
    { id: 'amicizia-con-gli-animali', name: 'Amicizia con gli Animali', level: 1, school: 'Incantamento',
      classes: ['bardo', 'druido', 'ranger'],
      meta: 'Azione · 9 m · 24 ore · V, S, M (un boccone di cibo)',
      desc: 'Una Bestia bersaglio fa TS Saggezza o è Affascinata per la durata. Se tu o un alleato le infliggete danno, l\'incantesimo termina subito. +1 bersaglio per ogni slot oltre il 1°.' },
    { id: 'colpo-avviluppante', name: 'Colpo Avviluppante', level: 1, school: 'Convocazione',
      classes: ['ranger'],
      meta: 'Azione bonus (dopo un colpo in mischia) · Sé · 1 min CONC · V',
      desc: 'Vigne afferrano il bersaglio, che fa TS Forza (svantaggiato se Grande o più) o è Afferrato. Mentre Afferrato subisce 1d6 perforanti a inizio di ogni suo turno; può liberarsi con una prova di Atletica contro la tua CD. +1d6 per ogni slot oltre il 1°.' },
    { id: 'aggrovigliare', name: 'Aggrovigliare', level: 1, school: 'Convocazione',
      classes: ['druido', 'ranger'],
      meta: 'Azione · 27 m · 1 min CONC · V, S',
      desc: 'Piante rampicanti riempiono un\'area di 6 m di lato, rendendola Terreno Difficile. Le creature presenti fanno TS Forza o sono Afferrate; possono liberarsi con una prova di Atletica contro la tua CD.' },
    { id: 'nube-di-nebbia', name: 'Nube di Nebbia', level: 1, school: 'Convocazione',
      classes: ['druido', 'ranger', 'stregone', 'mago'],
      meta: 'Azione · 36 m · 1 ora CONC · V, S',
      desc: 'Sfera di nebbia di 6 m di raggio, Fortemente Oscurata, finché dura o finché un vento forte (anche Raffica di Vento) non la disperde. +6 m di raggio per ogni slot oltre il 1°.' },
    { id: 'baccabuona', name: 'Baccabuona', level: 1, school: 'Convocazione',
      classes: ['druido', 'ranger'],
      meta: 'Azione · Sé · 24 ore · V, S, M (un rametto di vischio)',
      desc: 'Crei dieci bacche magiche: mangiarne una (azione bonus) cura 1 PF e sazia per un giorno. Le bacche non mangiate svaniscono alla fine della durata.' },
    { id: 'grandine-di-spine', name: 'Grandine di Spine', level: 1, school: 'Convocazione',
      classes: ['ranger'],
      meta: 'Azione bonus (subito dopo un attacco a distanza) · Sé · Istantaneo · V',
      desc: 'Una pioggia di spine scaturisce dalla tua arma o munizione. Il bersaglio e ogni creatura entro 1,5 m da esso fanno TS Destrezza, subendo 1d10 perforanti (metà se superano). +1d10 per ogni slot oltre il 1°.' },
    { id: 'marchio-del-cacciatore', name: 'Marchio del Cacciatore', level: 1, school: 'Divinazione',
      classes: ['ranger'],
      meta: 'Azione bonus · 27 m · 1 ora CONC · V',
      desc: 'Marchi una preda: ogni colpo contro di essa infligge +1d6 forza extra, e hai vantaggio nel rintracciarla. Se scende a 0 PF puoi spostare il marchio (azione bonus). Con slot di 3°-4° dura fino a 8 ore, con slot di 5°+ fino a 24 ore.' },
    { id: 'salto', name: 'Salto', level: 1, school: 'Trasmutazione',
      classes: ['druido', 'ranger', 'stregone', 'mago'],
      meta: 'Azione bonus · Tocco · 1 min · V, S, M (una zampa di cavalletta)',
      desc: 'La creatura toccata può saltare fino a 9 m spendendo 3 m di movimento, una volta per turno finché dura. +1 bersaglio per ogni slot oltre il 1°.' },
    { id: 'falcata', name: 'Falcata', level: 1, school: 'Trasmutazione',
      classes: ['bardo', 'druido', 'ranger', 'mago'],
      meta: 'Azione · Tocco · 1 ora · V, S, M (un pizzico di terra)',
      desc: 'La velocità della creatura toccata aumenta di 3 m finché dura. +1 bersaglio per ogni slot oltre il 1°.' },
    { id: 'parlare-con-gli-animali', name: 'Parlare con gli Animali', level: 1, school: 'Divinazione',
      classes: ['bardo', 'druido', 'ranger', 'warlock'],
      meta: 'Azione o Rituale · Sé · 10 min · V, S',
      desc: 'Per la durata comprendi e comunichi verbalmente con le Bestie. La maggior parte sa poco oltre sopravvivenza e compagnia, ma può darti informazioni su luoghi e pericoli vicini percepiti nell\'ultimo giorno.' },

    /* 2° livello */
    { id: 'messaggero-animale', name: 'Messaggero Animale', level: 2, school: 'Incantamento',
      classes: ['bardo', 'druido', 'ranger'],
      meta: 'Azione o Rituale · 9 m · 24 ore · V, S, M (un boccone di cibo)',
      desc: 'Una piccola Bestia consegna un messaggio di massimo 25 parole a un destinatario descritto, percorrendo circa 40 km al giorno (80 se vola). Se non arriva prima della fine della durata, il messaggio va perso. +48 ore di durata per ogni slot oltre il 2°.' },
    { id: 'pelle-corticata', name: 'Pelle Corticata', level: 2, school: 'Trasmutazione',
      classes: ['druido', 'ranger'],
      meta: 'Azione bonus · Tocco · 1 ora · V, S, M (una manciata di corteccia)',
      desc: 'La pelle della creatura toccata assume un aspetto corticato: la sua CA diventa 17 se era inferiore, finché dura.' },
    { id: 'sensi-bestiali', name: 'Sensi Bestiali', level: 2, school: 'Divinazione',
      classes: ['druido', 'ranger'],
      meta: 'Azione o Rituale · Tocco · 1 ora CONC · S',
      desc: 'Percepisci attraverso i sensi di una Bestia volontaria toccata, inclusi eventuali sensi speciali, finché dura.' },
    { id: 'cordone-di-frecce', name: 'Cordone di Frecce', level: 2, school: 'Trasmutazione',
      classes: ['ranger'],
      meta: 'Azione · Tocco · 8 ore · V, S, M (una treccia ornamentale)',
      desc: 'Pianti fino a quattro frecce o quadrelli non magici nel terreno: se una creatura non esclusa entra entro 9 m o vi termina il turno, una munizione vola a colpirla (TS Destrezza, 2d4 perforanti se fallita) e si distrugge. Finisce quando le munizioni si esauriscono. +2 munizioni per ogni slot oltre il 2°.' },
    { id: 'scurovisione', name: 'Scurovisione', level: 2, school: 'Trasmutazione',
      classes: ['druido', 'ranger', 'stregone', 'mago'],
      meta: 'Azione · Tocco · 8 ore · V, S, M (una carota essiccata)',
      desc: 'La creatura volontaria toccata ottiene Scurovisione 45 m per la durata.' },
    { id: 'potenziare-abilita', name: 'Potenziare Abilità', level: 2, school: 'Trasmutazione',
      classes: ['bardo', 'chierico', 'druido', 'ranger', 'stregone', 'mago'],
      meta: 'Azione · Tocco · 1 ora CONC · V, S, M (pelo o una piuma)',
      desc: 'La creatura toccata ha vantaggio alle prove con una caratteristica a scelta finché dura. +1 bersaglio (con caratteristica scelta a parte) per ogni slot oltre il 2°.' },
    { id: 'individuare-trappole', name: 'Individuare Trappole', level: 2, school: 'Divinazione',
      classes: ['chierico', 'druido', 'ranger'],
      meta: 'Azione · 36 m · Istantaneo · V, S',
      desc: 'Percepisci la presenza (non la posizione esatta) di ogni trappola in linea di vista entro gittata, incluse quelle magiche come Allarme o Glifo di Custodia, e ne apprendi la natura generale del pericolo.' },
    { id: 'raffica-di-vento', name: 'Raffica di Vento', level: 2, school: 'Evocazione',
      classes: ['druido', 'ranger', 'stregone', 'mago'],
      meta: 'Azione · Sé · 1 min CONC · V, S, M (un seme di legume)',
      desc: 'Una linea di vento forte lunga 18 m e larga 3 m si irradia da te. Le creature nella linea fanno TS Forza o sono spinte di 4,5 m; disperde gas/vapori e spegne fiamme non protette. Azione bonus per cambiare direzione nei turni successivi.' },
    { id: 'individuare-animali-o-piante', name: 'Individuare Animali o Piante', level: 2, school: 'Divinazione',
      classes: ['bardo', 'druido', 'ranger'],
      meta: 'Azione o Rituale · Sé · Istantaneo · V, S, M (pelo di segugio)',
      desc: 'Descrivi un tipo di Bestia, Pianta o pianta non magica: apprendi direzione e distanza dell\'esemplare più vicino entro 8 km, se presente.' },
    { id: 'passo-senza-tracce', name: 'Passo senza Tracce', level: 2, school: 'Abiurazione',
      classes: ['druido', 'ranger'],
      meta: 'Azione · Sé (emanazione 9 m) · 1 ora CONC · V, S, M (cenere di vischio bruciato)',
      desc: 'Un\'aura ti segue: tu e chi scegli entro l\'emanazione ottenete +10 alle prove di Furtività e non lasciate tracce, finché dura.' },
    { id: 'silenzio', name: 'Silenzio', level: 2, school: 'Illusione',
      classes: ['bardo', 'chierico', 'ranger'],
      meta: 'Azione o Rituale · 36 m · 10 min CONC · V, S',
      desc: 'Sfera di 6 m di raggio in cui nessun suono può nascere o propagarsi: chi vi è interamente dentro è immune al Tuono ed è Assordato; lanciare incantesimi con componente Verbale lì dentro è impossibile.' },
    { id: 'crescita-di-spuntoni', name: 'Crescita di Spuntoni', level: 2, school: 'Trasmutazione',
      classes: ['druido', 'ranger'],
      meta: 'Azione · 45 m · 10 min CONC · V, S, M (sette spine)',
      desc: 'Il terreno in una sfera di 6 m di raggio si ricopre di spuntoni: diventa Terreno Difficile e chi vi si muove attraverso subisce 2d4 perforanti ogni 1,5 m percorsi. Il terreno appare naturale finché non lo si individua con una prova di Percezione o Sopravvivenza.' },
    { id: 'evocare-bestia', name: 'Evocare Bestia', level: 2, school: 'Convocazione',
      classes: ['druido', 'ranger'],
      meta: 'Azione · 27 m · 1 ora CONC · V, S, M (piuma, ciuffo di pelo e coda di pesce in una ghianda dorata, 200+ MO)',
      desc: 'Evochi uno spirito bestiale (statistiche proprie) scegliendo l\'ambiente Aria, Terra o Mare: combatte al tuo fianco condividendo la tua iniziativa e obbedendo ai tuoi comandi.' },

    /* 3° livello */
    { id: 'evocare-animali', name: 'Evocare Animali', level: 3, school: 'Convocazione',
      classes: ['druido', 'ranger'],
      meta: 'Azione · 18 m · 10 min CONC · V, S',
      desc: 'Evochi un branco spettrale di animali (forma a scelta) che puoi muovere insieme a te. Vantaggio ai TS Forza mentre sei entro 1,5 m dal branco; le creature vicine fanno TS Destrezza o subiscono 3d10 taglienti (una volta a turno). +1d10 per ogni slot oltre il 3°.' },
    { id: 'raffica-evocata', name: 'Raffica Evocata', level: 3, school: 'Convocazione',
      classes: ['ranger'],
      meta: 'Azione · Sé · Istantaneo · V, S, M (un\'arma da mischia o a distanza, valore 1+ MR)',
      desc: 'Brandisci l\'arma e conjuri armi spettrali simili che si scagliano in un Cono di 18 m. Le creature scelte fanno TS Destrezza, subendo 5d8 forza (metà se superano). +1d8 per ogni slot oltre il 3°.' },
    { id: 'freccia-fulminante', name: 'Freccia Fulminante', level: 3, school: 'Trasmutazione',
      classes: ['ranger'],
      meta: 'Azione bonus (subito dopo un colpo o un fallimento a distanza) · Sé · Istantaneo · V, S',
      desc: 'L\'arma o munizione si trasforma in un fulmine: il bersaglio subisce 4d8 fulmine (metà se l\'attacco era un fallimento) invece del danno normale; le creature entro 3 m fanno TS Destrezza per 2d8 fulmine (metà se superano). +1d8 a entrambi gli effetti per ogni slot oltre il 3°.' },
    { id: 'fondersi-con-la-pietra', name: 'Fondersi con la Pietra', level: 3, school: 'Trasmutazione',
      classes: ['chierico', 'druido', 'ranger'],
      meta: 'Azione o Rituale · Tocco · 8 ore · V, S',
      desc: 'Ti fondi con una superficie di pietra abbastanza grande da contenerti: nulla della tua presenza resta visibile o rilevabile con mezzi non magici finché dura.' },
    { id: 'non-individuazione', name: 'Non Individuazione', level: 3, school: 'Abiurazione',
      classes: ['bardo', 'ranger', 'mago'],
      meta: 'Azione · Tocco · 8 ore · V, S, M (polvere di diamante da 25+ MO, consumata)',
      desc: 'Nascondi un bersaglio toccato (creatura, luogo o oggetto fino a 3 m di lato) dagli incantesimi di divinazione e dagli occhi magici per la durata.' },
    { id: 'crescita-delle-piante', name: 'Crescita delle Piante', level: 3, school: 'Trasmutazione',
      classes: ['bardo', 'druido', 'ranger'],
      meta: 'Azione (Rigoglio) o 8 ore (Arricchimento) · 45 m · Istantaneo · V, S',
      desc: 'Rigoglio: le piante in una sfera di 30 m di raggio diventano fitte e Terreno Difficile (puoi escludere aree a scelta). Arricchimento: le piante in 800 m di raggio danno il doppio del raccolto per 365 giorni (un solo utilizzo l\'anno per area).' },
    { id: 'protezione-dall-energia', name: 'Protezione dall\'Energia', level: 3, school: 'Abiurazione',
      classes: ['chierico', 'druido', 'ranger', 'stregone', 'mago'],
      meta: 'Azione · Tocco · 1 ora CONC · V, S',
      desc: 'La creatura volontaria toccata ottiene resistenza a un tipo di danno a scelta tra acido, freddo, fuoco, fulmine o tuono, finché dura.' },
    { id: 'parlare-con-le-piante', name: 'Parlare con le Piante', level: 3, school: 'Trasmutazione',
      classes: ['bardo', 'druido', 'ranger'],
      meta: 'Azione · Sé (emanazione 9 m) · 10 min · V, S',
      desc: 'Doni sentienza limitata alle piante nell\'emanazione: puoi interrogarle su eventi dell\'ultimo giorno e trasformare Terreno Difficile vegetale in normale (o viceversa) per la durata.' },
    { id: 'evocare-folletto', name: 'Evocare Folletto', level: 3, school: 'Convocazione',
      classes: ['druido', 'ranger', 'warlock', 'mago'],
      meta: 'Azione · 27 m · 1 ora CONC · V, S, M (un fiore dorato, 300+ MO)',
      desc: 'Evochi uno spirito fatato (statistiche proprie) scegliendo l\'umore Furente, Gioioso o Beffardo: combatte al tuo fianco condividendo la tua iniziativa e obbedendo ai tuoi comandi.' },
    { id: 'respirare-in-acqua', name: 'Respirare in Acqua', level: 3, school: 'Trasmutazione',
      classes: ['druido', 'ranger', 'stregone', 'mago'],
      meta: 'Azione o Rituale · 9 m · 24 ore · V, S, M (una canna corta)',
      desc: 'Fino a dieci creature volontarie entro gittata possono respirare sott\'acqua per la durata, mantenendo anche la respirazione normale.' },
    { id: 'camminare-sull-acqua', name: 'Camminare sull\'Acqua', level: 3, school: 'Trasmutazione',
      classes: ['chierico', 'druido', 'ranger', 'stregone'],
      meta: 'Azione o Rituale · 9 m · 1 ora · V, S, M (un pezzo di sughero)',
      desc: 'Fino a dieci creature volontarie entro gittata possono muoversi su qualsiasi superficie liquida come se fosse terreno solido per la durata (azione bonus per passare da e verso il liquido).' },
    { id: 'muro-di-vento', name: 'Muro di Vento', level: 3, school: 'Evocazione',
      classes: ['druido', 'ranger'],
      meta: 'Azione · 36 m · 1 min CONC · V, S, M (un ventaglio e una piuma)',
      desc: 'Un muro di vento forte (fino a 15 m lungo, 4,5 m alto, in un percorso continuo) sorge dal terreno. Le creature nell\'area fanno TS Forza o subiscono 4d8 contundenti (metà se superano); tiene a bada gas e fumi, blocca creature volanti Piccole o più piccole, devia proiettili ordinari lanciati attraverso di esso e impedisce il passaggio a creature in forma gassosa.' },

    /* 4° livello */
    { id: 'evocare-creature-silvane', name: 'Evocare Creature Silvane', level: 4, school: 'Convocazione',
      classes: ['druido', 'ranger'],
      meta: 'Azione · Sé (emanazione 3 m) · 10 min CONC · V, S',
      desc: 'Spiriti della natura ti volteggiano attorno nell\'emanazione. Le creature che vi entrano o vi terminano il turno fanno TS Saggezza o subiscono 5d8 forza (metà se superano, una volta a turno). Azione bonus per Disimpegnarti per la durata. +1d8 per ogni slot oltre il 5°.' },
    { id: 'dominare-bestia', name: 'Dominare Bestia', level: 4, school: 'Incantamento',
      classes: ['druido', 'ranger', 'stregone'],
      meta: 'Azione · 18 m · 1 min CONC · V, S',
      desc: 'Una Bestia fa TS Saggezza (con vantaggio se in combattimento contro di te) o è Affascinata: le impartisci comandi telepatici finché dura. Ripete il TS ogni volta che subisce danno. Con slot di 5° dura 10 minuti, 6° un\'ora, 7°+ otto ore.' },
    { id: 'liberta-di-movimento', name: 'Libertà di Movimento', level: 4, school: 'Abiurazione',
      classes: ['bardo', 'chierico', 'druido', 'ranger'],
      meta: 'Azione · Tocco · 1 ora · V, S, M (una cinghia di cuoio)',
      desc: 'La creatura toccata ignora il Terreno Difficile, non può subire riduzioni di velocità né Paralisi/Restrizione da magia, e ottiene velocità di nuoto pari alla sua. Può spendere 1,5 m di movimento per liberarsi automaticamente da manette o Afferramento non magici. +1 bersaglio per ogni slot oltre il 4°.' },
    { id: 'vite-afferrante', name: 'Vite Afferrante', level: 4, school: 'Convocazione',
      classes: ['druido', 'ranger'],
      meta: 'Azione bonus · 18 m · 1 min CONC · V, S',
      desc: 'Convochi una vite che spunta da una superficie. Attacco con incantesimo in mischia contro una creatura entro 9 m dalla vite: se colpisci, 4d8 contundenti e la trascini fino a 9 m verso di essa, Afferrandola se non più grande di Enorme. Azione bonus per ripetere l\'attacco nei turni successivi. +1 creatura afferrabile per ogni slot oltre il 4°.' },
    { id: 'pelle-di-pietra', name: 'Pelle di Pietra', level: 4, school: 'Trasmutazione',
      classes: ['druido', 'ranger', 'stregone', 'mago'],
      meta: 'Azione · Tocco · 1 ora CONC · V, S, M (polvere di diamante da 100+ MO, consumata)',
      desc: 'La creatura volontaria toccata ottiene resistenza ai danni contundenti, perforanti e taglienti finché dura.' },
    { id: 'evocare-elementale', name: 'Evocare Elementale', level: 4, school: 'Convocazione',
      classes: ['druido', 'ranger', 'mago'],
      meta: 'Azione · 27 m · 1 ora CONC · V, S, M (aria, un sasso, cenere e acqua in una fiala dorata, 400+ MO)',
      desc: 'Evochi uno spirito elementale (statistiche proprie) scegliendo Aria, Terra, Fuoco o Acqua: combatte al tuo fianco condividendo la tua iniziativa e obbedendo ai tuoi comandi.' },

    /* 5° livello */
    { id: 'comunione-con-la-natura', name: 'Comunione con la Natura', level: 5, school: 'Divinazione',
      classes: ['druido', 'ranger'],
      meta: '1 minuto o Rituale · Sé · Istantaneo · V, S',
      desc: 'Ti sintonizzi con gli spiriti della natura entro 4,8 km all\'aperto (90 m in ambienti sotterranei naturali). Scegli tre informazioni tra: insediamenti, portali, e posizione di una creatura ultraterrena di GS 10+.' },
    { id: 'scarica-evocata', name: 'Scarica Evocata', level: 5, school: 'Convocazione',
      classes: ['ranger'],
      meta: 'Azione · 45 m · Istantaneo · V, S, M (un\'arma da mischia o a distanza, valore 1+ MR)',
      desc: 'Brandisci l\'arma e scegli un punto entro gittata: centinaia di armi spettrali si abbattono in un Cilindro di 12 m di raggio e 6 m di altezza. Le creature scelte fanno TS Destrezza, subendo 8d8 forza (metà se superano).' },
    { id: 'vento-d-acciaio', name: 'Colpo del Vento d\'Acciaio', level: 5, school: 'Convocazione',
      classes: ['ranger', 'mago'],
      meta: 'Azione · 9 m · Istantaneo · S, M (un\'arma da mischia, valore 1+ MA)',
      desc: 'Ti sposti come il vento colpendo fino a cinque creature scelte entro gittata: attacco con incantesimo in mischia contro ciascuna, 6d10 forza a chi viene colpito. Poi ti teletrasporti entro 1,5 m da uno dei bersagli.' },
    { id: 'faretra-rapida', name: 'Faretra Rapida', level: 5, school: 'Trasmutazione',
      classes: ['ranger'],
      meta: 'Azione bonus · Sé · 1 min CONC · V, S, M (una faretra, valore 1+ MO)',
      desc: 'Finché dura, ogni azione bonus ti permette due attacchi extra con un\'arma che scaglia frecce o quadrelli: l\'incantesimo crea la munizione necessaria, che si disintegra subito dopo colpire o mancare.' },
    { id: 'passo-arboreo', name: 'Passo Arboreo', level: 5, school: 'Convocazione',
      classes: ['druido', 'ranger'],
      meta: 'Azione · Sé · 1 min CONC · V, S',
      desc: 'Puoi entrare in un albero e spostarti dentro un altro albero della stessa specie entro 150 m, spendendo 1,5 m di movimento per ciascun passaggio. Puoi farlo una sola volta per turno e devi terminare ogni turno fuori da un albero.' },

    /* ===== Warlock — trucchetti e 1°-2° livello (blocco 1) ===== */
    { id: 'guardia-della-lama', name: 'Guardia della Lama', level: 0, school: 'Abiurazione',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · Sé · 1 min CONC · V, S',
      desc: 'Finché dura, ogni creatura che ti attacca sottrae 1d4 al tiro per colpire.' },
    { id: 'tocco-agghiacciante', name: 'Tocco Agghiacciante', level: 0, school: 'Negromanzia',
      classes: ['stregone', 'warlock', 'mago'],
      meta: 'Azione · Tocco · Istantaneo · V, S',
      desc: 'Attacco con incantesimo in mischia: se colpisci, 1d10 necrotici e il bersaglio non può recuperare PF fino alla fine del tuo prossimo turno. Il danno sale a 2d10 al livello 5, 3d10 all\'11°, 4d10 al 17°.' },
    { id: 'raggio-occulto', name: 'Raggio Occulto', level: 0, school: 'Evocazione',
      classes: ['warlock'],
      meta: 'Azione · 36 m · Istantaneo · V, S',
      desc: 'Attacco con incantesimo a distanza: 1d10 forza se colpisci. Dal livello 5 lanci due raggi, dall\'11° tre, dal 17° quattro; ogni raggio ha un tiro per colpire separato e puoi dividerli su bersagli diversi.' },
    { id: 'amici', name: 'Amici', level: 0, school: 'Incantamento',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 3 m · 1 min CONC · S, M (trucco per il viso)',
      desc: 'Una creatura entro gittata fa TS Saggezza o è Affascinata finché dura (successo automatico se non è Umanoide, se ti sta combattendo, o se già bersaglio nelle ultime 24 ore).' },
    { id: 'mano-magica', name: 'Mano Magica', level: 0, school: 'Convocazione',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 9 m · 1 min · V, S',
      desc: 'Una mano spettrale manipola oggetti, apre porte o contenitori non chiusi a chiave, o versa il contenuto di una fiala. Non può attaccare, attivare oggetti magici, né portare più di 4,5 kg. Azione magica nei turni successivi per muoverla fino a 9 m.' },
    { id: 'scheggia-mentale', name: 'Scheggia Mentale', level: 0, school: 'Incantamento',
      classes: ['stregone', 'warlock', 'mago'],
      meta: 'Azione · 18 m · 1 round · V',
      desc: 'Il bersaglio fa TS Intelligenza o subisce 1d6 psichici e sottrae 1d4 al suo prossimo TS entro la fine del tuo prossimo turno. Il danno sale a 2d6 al livello 5, 3d6 all\'11°, 4d6 al 17°.' },
    { id: 'illusione-minore', name: 'Illusione Minore', level: 0, school: 'Illusione',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 9 m · 1 min · S, M (un fiocco di lana)',
      desc: 'Crei un suono o l\'immagine di un oggetto entro gittata, finché dura o finché non lanci di nuovo l\'incantesimo. Una creatura che la esamina con un\'azione di Studio può smascherarla con una prova di Investigare contro la tua CD.' },
    { id: 'spruzzo-di-veleno', name: 'Spruzzo di Veleno', level: 0, school: 'Negromanzia',
      classes: ['druido', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 9 m · Istantaneo · V, S',
      desc: 'Attacco con incantesimo a distanza: 1d12 veleno se colpisci. Il danno sale a 2d12 al livello 5, 3d12 all\'11°, 4d12 al 17°.' },
    { id: 'prestidigitazione', name: 'Prestidigitazione', level: 0, school: 'Trasmutazione',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 3 m · fino a 1 ora · V, S',
      desc: 'Crei uno tra vari piccoli effetti magici a scelta (scintille o odori innocui, accendere/spegnere una piccola fiamma, pulire o sporcare un oggetto, un piccolo segno colorato, un gingillo illusorio in mano). Puoi mantenerne fino a tre non istantanei attivi insieme.' },
    { id: 'schiocco-di-tuono', name: 'Schiocco di Tuono', level: 0, school: 'Evocazione',
      classes: ['bardo', 'druido', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · Sé (emanazione 1,5 m) · Istantaneo · S',
      desc: 'Le creature nell\'emanazione fanno TS Costituzione o subiscono 1d6 tuono; il suono si sente fino a 30 m. Il danno sale a 2d6 al livello 5, 3d6 all\'11°, 4d6 al 17°.' },
    { id: 'rintocco-dei-morti', name: 'Rintocco dei Morti', level: 0, school: 'Negromanzia',
      classes: ['chierico', 'warlock', 'mago'],
      meta: 'Azione · 18 m · Istantaneo · V, S',
      desc: 'Il bersaglio fa TS Saggezza o subisce 1d8 necrotici (1d12 se già ferito). Ai livelli 5/11/17 il dado aumenta (2d8 o 2d12, poi 3, poi 4).' },
    { id: 'vero-colpo', name: 'Vero Colpo', level: 0, school: 'Divinazione',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · Sé · Istantaneo · S, M (un\'arma con cui hai competenza, valore 1+ MR)',
      desc: 'Un solo attacco con l\'arma usata nel lancio, usando la tua caratteristica da incantatore invece di Forza o Destrezza; il danno può essere Radioso o quello normale dell\'arma. Ai livelli 5/11/17 aggiunge danno Radioso extra (1d6, poi 2d6, poi 3d6).' },

    { id: 'armatura-di-agathys', name: 'Armatura di Agathys', level: 1, school: 'Abiurazione',
      classes: ['warlock'],
      meta: 'Azione bonus · Sé · 1 ora · V, S, M (un frammento di vetro blu)',
      desc: 'Ottieni 5 PF temporanei. Finché dura, ogni creatura che ti colpisce in mischia subisce 5 danni da freddo. Termina prima se perdi tutti i PF temporanei. +5 PF temporanei e +5 danni per ogni slot oltre il 1°.' },
    { id: 'braccia-di-hadar', name: 'Braccia di Hadar', level: 1, school: 'Convocazione',
      classes: ['warlock'],
      meta: 'Azione · Sé (emanazione 3 m) · Istantaneo · V, S',
      desc: 'Tentacoli scaturiscono da te: le creature nell\'emanazione fanno TS Forza, subendo 2d6 necrotici (metà se superano) e non potendo usare reazioni fino al tuo prossimo turno. +1d6 per ogni slot oltre il 1°.' },
    { id: 'maledizione', name: 'Maledizione', level: 1, school: 'Incantamento',
      classes: ['bardo', 'chierico', 'warlock'],
      meta: 'Azione · 9 m · 1 min CONC · V, S, M (una goccia di sangue)',
      desc: 'Fino a tre creature fanno TS Carisma; chi fallisce sottrae 1d4 ai tiri per colpire e ai TS finché dura. +1 bersaglio per ogni slot oltre il 1°.' },
    { id: 'ammaliare-persone', name: 'Ammaliare Persone', level: 1, school: 'Incantamento',
      classes: ['bardo', 'druido', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 9 m · 1 ora · V, S',
      desc: 'Un Umanoide fa TS Saggezza (con vantaggio se in combattimento con te) o è Affascinato finché dura o finché tu/alleati gli infliggete danno. +1 bersaglio per ogni slot oltre il 1°.' },
    { id: 'comprendere-le-lingue', name: 'Comprendere le Lingue', level: 1, school: 'Divinazione',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione o Rituale · Sé · 1 ora · V, S, M (fuliggine e sale)',
      desc: 'Comprendi il significato letterale di qualsiasi lingua che senti o vedi segnata, incluse quelle scritte se tocchi il testo. Non decodifica simboli o messaggi in codice.' },
    { id: 'ritirata-veloce', name: 'Ritirata Veloce', level: 1, school: 'Trasmutazione',
      classes: ['stregone', 'warlock', 'mago'],
      meta: 'Azione bonus · Sé · 10 min CONC · V, S',
      desc: 'Compi l\'azione Scatto, e finché dura puoi ripeterla come azione bonus in ogni turno successivo.' },
    { id: 'rimprovero-infernale', name: 'Rimprovero Infernale', level: 1, school: 'Evocazione',
      classes: ['warlock'],
      meta: 'Reazione (a un danno subito da una creatura vista entro 18 m) · 18 m · Istantaneo · V, S',
      desc: 'La creatura che ti ha danneggiato fa TS Destrezza, subendo 2d10 fuoco (metà se supera). +1d10 per ogni slot oltre il 1°.' },
    { id: 'fattura', name: 'Fattura', level: 1, school: 'Incantamento',
      classes: ['warlock'],
      meta: 'Azione bonus · 27 m · 1 ora CONC · V, S, M (occhio pietrificato di tritone)',
      desc: 'Maledici un bersaglio: ogni colpo gli infligge +1d6 necrotico extra, e ha svantaggio alle prove con una caratteristica a scelta. Se scende a 0 PF puoi spostare la maledizione (azione bonus). Con slot di 2° dura 4 ore, 3°-4° otto ore, 5°+ ventiquattro ore.' },
    { id: 'scrittura-illusoria', name: 'Scrittura Illusoria', level: 1, school: 'Illusione',
      classes: ['bardo', 'warlock', 'mago'],
      meta: '1 minuto o Rituale · Tocco · 10 giorni · S, M (inchiostro da 10+ MO, consumato)',
      desc: 'Scrivi un testo che appare normale solo a te e a chi designi; per chiunque altro è uno script illeggibile (o puoi alterarne il significato apparente). Chi ha Vista Vera legge comunque il messaggio nascosto.' },
    { id: 'risata-orrenda-di-tasha', name: 'Risata Orrenda di Tasha', level: 1, school: 'Incantamento',
      classes: ['bardo', 'warlock', 'mago'],
      meta: 'Azione · 9 m · 1 min CONC · V, S, M (una torta e una piuma)',
      desc: 'Il bersaglio fa TS Saggezza o è Prono e Incapace di Agire, ridendo senza controllo, finché dura. Ripete il TS (con vantaggio se scatenato da un danno) a fine turno e quando subisce danno; se supera, l\'incantesimo termina. +1 bersaglio per ogni slot oltre il 1°.' },
    { id: 'servitore-invisibile', name: 'Servitore Invisibile', level: 1, school: 'Convocazione',
      classes: ['bardo', 'warlock', 'mago'],
      meta: 'Azione o Rituale · 18 m · 1 ora · V, S, M (spago e legno)',
      desc: 'Crei una forza invisibile e priva di mente (CA 10, 1 PF, For 2) che compie compiti semplici (portare oggetti, pulire, servire, versare) su tuo comando mentale: azione bonus per muoverla fino a 4,5 m. Termina a 0 PF.' },
    { id: 'dardo-stregato', name: 'Dardo Stregato', level: 1, school: 'Evocazione',
      classes: ['stregone', 'warlock', 'mago'],
      meta: 'Azione · 18 m · 1 min CONC · V, S, M (un rametto colpito da un fulmine)',
      desc: 'Attacco con incantesimo a distanza: 2d12 fulmine se colpisci, poi un arco di energia resta sospeso. Nei turni successivi, azione bonus per infliggere automaticamente 1d12 fulmine, anche se il primo attacco mancò. Termina se il bersaglio esce dalla gittata o ha copertura totale. +1d12 al danno iniziale per ogni slot oltre il 1°.' },

    { id: 'nube-di-pugnali', name: 'Nube di Pugnali', level: 2, school: 'Convocazione',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 18 m · 1 min CONC · V, S, M (una scheggia di vetro)',
      desc: 'Pugnali roteanti riempiono un cubo di 1,5 m: chi vi entra o vi termina il turno subisce 4d4 taglienti (una volta a turno). Azione magica per teletrasportare il cubo fino a 9 m. +2d4 per ogni slot oltre il 2°.' },
    { id: 'corona-di-follia', name: 'Corona di Follia', level: 2, school: 'Incantamento',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 36 m · 1 min CONC · V, S',
      desc: 'Una creatura (fallisce automaticamente se non è Umanoide) fa TS Saggezza o è Affascinata: una corona spettrale le appare in testa e, a ogni suo turno, deve attaccare in mischia la creatura più vicina a scelta tua (o agisce normalmente se non ne scegli una o nessuna è a portata). Ripete il TS a fine turno; devi mantenere il controllo con un\'azione magica ogni turno successivo, altrimenti l\'incantesimo termina.' },
    { id: 'oscurita', name: 'Oscurità', level: 2, school: 'Evocazione',
      classes: ['stregone', 'warlock', 'mago'],
      meta: 'Azione · 18 m · 10 min CONC · V, M (pelo di pipistrello e un pezzo di carbone)',
      desc: 'Oscurità magica riempie una sfera di 4,5 m di raggio (o un\'emanazione se lanciata su un oggetto non indossato): la Scurovisione non la penetra e la luce non magica non la illumina. Dissolve luce di livello 2 o inferiore che vi si sovrappone; coprire l\'oggetto sorgente con qualcosa di opaco blocca l\'effetto.' },
    { id: 'soggiogare', name: 'Soggiogare', level: 2, school: 'Incantamento',
      classes: ['bardo', 'warlock'],
      meta: 'Azione · 18 m · 1 min CONC · V, S',
      desc: 'Le creature scelte entro gittata fanno TS Saggezza (successo automatico se ti stanno già combattendo) o subiscono −10 alle prove di Percezione e alla Percezione passiva finché dura.' },
    { id: 'paralizzare-umanoide', name: 'Paralizzare Umanoide', level: 2, school: 'Incantamento',
      classes: ['bardo', 'chierico', 'druido', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 18 m · 1 min CONC · V, S, M (un pezzo di ferro dritto)',
      desc: 'Un Umanoide fa TS Saggezza o è Paralizzato finché dura, ripetendo il TS a fine di ogni suo turno. +1 bersaglio per ogni slot oltre il 2°.' },
    { id: 'invisibilita', name: 'Invisibilità', level: 2, school: 'Illusione',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · Tocco · 1 ora CONC · V, S, M (un ciglio in gomma arabica)',
      desc: 'La creatura toccata è Invisibile finché dura; termina subito dopo che attacca, infligge danno o lancia un incantesimo. +1 bersaglio per ogni slot oltre il 2°.' },
    { id: 'puntura-mentale', name: 'Puntura Mentale', level: 2, school: 'Divinazione',
      classes: ['stregone', 'warlock', 'mago'],
      meta: 'Azione · 36 m · 1 ora CONC · S',
      desc: 'Il bersaglio fa TS Saggezza, subendo 3d8 psichici (metà se supera). Se fallisce, ne conosci sempre la posizione finché dura (stesso piano) e non può nascondersi da te né beneficiare dell\'Invisibilità contro di te. +1d8 per ogni slot oltre il 2°.' },
    { id: 'immagine-speculare', name: 'Immagine Speculare', level: 2, school: 'Illusione',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · Sé · 1 min · V, S',
      desc: 'Tre duplicati illusori ti circondano, muovendosi e imitandoti. Se subisci un colpo, tiri 1d6 per ogni duplicato rimasto: con un 3+ un duplicato viene colpito al posto tuo e distrutto. Finisce quando tutti e tre sono distrutti; non inganna le creature Accecate o dotate di Vista Cieca o Vista Vera.' },
    { id: 'passo-nella-nebbia', name: 'Passo nella Nebbia', level: 2, school: 'Convocazione',
      classes: ['stregone', 'warlock', 'mago'],
      meta: 'Azione bonus · Sé · Istantaneo · V',
      desc: 'Avvolto da nebbia argentea, ti teletrasporti fino a 9 m in uno spazio libero che riesci a vedere.' },
    { id: 'raggio-di-indebolimento', name: 'Raggio di Indebolimento', level: 2, school: 'Negromanzia',
      classes: ['warlock', 'mago'],
      meta: 'Azione · 18 m · 1 min CONC · V, S',
      desc: 'Il bersaglio fa TS Costituzione. Se fallisce, ha svantaggio ai D20 Test basati su Forza e sottrae 1d8 ai tiri per i danni finché dura (ripete il TS a fine turno). Se supera, ha solo svantaggio al suo prossimo attacco.' },
    { id: 'scalare-come-ragno', name: 'Scalare come Ragno', level: 2, school: 'Trasmutazione',
      classes: ['stregone', 'warlock', 'mago'],
      meta: 'Azione · Tocco · 1 ora CONC · V, S, M (una goccia di bitume e un ragno)',
      desc: 'La creatura volontaria toccata può muoversi su superfici verticali e soffitti senza usare le mani, con velocità di scalata pari alla sua, finché dura. +1 bersaglio per ogni slot oltre il 2°.' },
    { id: 'suggestione', name: 'Suggestione', level: 2, school: 'Incantamento',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 9 m · 8 ore CONC · V, M (una goccia di miele)',
      desc: 'Suggerisci (max 25 parole) un\'attività plausibile e non dannosa a un bersaglio che ti capisce. Fa TS Saggezza o è Affascinato e la persegue finché dura o finché tu/alleati gli infliggete danno; se la completa prima, l\'incantesimo termina su di esso.' },

    /* ===== Warlock — 3°-9° livello (blocco 2, completa la classe) ===== */
    { id: 'contro-incantesimo', name: 'Contro Incantesimo', level: 3, school: 'Abiurazione',
      classes: ['stregone', 'warlock', 'mago'],
      meta: 'Reazione (a una creatura vista entro 18 m che lancia un incantesimo con componente Verbale, Somatica o Materiale) · 18 m · Istantaneo · S',
      desc: 'Il lanciatore fa TS Costituzione contro la tua CD incantesimi: se fallisce, l\'incantesimo si dissolve senza effetto e l\'azione (o lo slot, se usato) è sprecata.' },
    { id: 'paura', name: 'Paura', level: 3, school: 'Illusione',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · Sé (cono 9 m) · 1 min CONC · V, S, M (una piuma bianca)',
      desc: 'Le creature nel cono fanno TS Saggezza o lasciano cadere ciò che tengono in mano e sono Spaventate finché dura. Una creatura Spaventata usa Scatto per allontanarsi da te ogni turno; se termina il turno senza linea di vista su di te, ripete il TS per liberarsi.' },
    { id: 'volare', name: 'Volare', level: 3, school: 'Trasmutazione',
      classes: ['stregone', 'warlock', 'mago'],
      meta: 'Azione · Tocco · 10 min CONC · V, S, M (una piuma)',
      desc: 'La creatura volontaria toccata ottiene velocità di volo di 18 m e può librarsi, finché dura. Se è ancora in volo quando l\'incantesimo termina, cade (a meno che non possa fermare la caduta). +1 bersaglio per ogni slot oltre il 3°.' },
    { id: 'forma-gassosa', name: 'Forma Gassosa', level: 3, school: 'Trasmutazione',
      classes: ['stregone', 'warlock', 'mago'],
      meta: 'Azione · Tocco · 1 ora CONC · V, S, M (un pezzo di garza)',
      desc: 'La creatura volontaria toccata si trasforma (con tutto ciò che indossa e porta) in una nube di nebbia: volo 3 m con librarsi come unico movimento, può entrare nello spazio di un\'altra creatura, resistenza a contundenti/perforanti/taglienti, immunità a Prono, vantaggio ai TS Forza/Destrezza/Costituzione. Non può parlare, manipolare oggetti, attaccare né lanciare incantesimi. Termina a 0 PF o con un\'azione magica. +1 bersaglio per ogni slot oltre il 3°.' },
    { id: 'fame-di-hadar', name: 'Fame di Hadar', level: 3, school: 'Convocazione',
      classes: ['warlock'],
      meta: 'Azione · 45 m · 1 min CONC · V, S, M (un tentacolo sottaceto)',
      desc: 'Apri un varco verso il Regno Remoto: una sfera di oscurità di 6 m di raggio appare, Terreno Difficile, piena di sussurri udibili a 9 m; nessuna luce la illumina e chi vi è interamente dentro è Accecato. Chi inizia il turno nell\'area subisce 2d6 freddo; chi lo termina lì fa TS Destrezza per 2d6 acido da tentacoli (metà se supera). +1d6 a un danno a scelta per ogni slot oltre il 3°.' },
    { id: 'motivo-ipnotico', name: 'Motivo Ipnotico', level: 3, school: 'Illusione',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 36 m · 1 min CONC · S, M (un pizzico di coriandoli)',
      desc: 'Un motivo di colori intrecciati appare in un cubo di 9 m entro gittata. Chi lo vede fa TS Saggezza o è Affascinato (Incapace di Agire, velocità 0) finché dura. Termina per una creatura se subisce danno o se qualcuno la scuote con un\'azione.' },
    { id: 'immagine-maggiore', name: 'Immagine Maggiore', level: 3, school: 'Illusione',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 36 m · 10 min CONC · V, S, M (un fiocco di lana)',
      desc: 'Crei l\'immagine (con suoni, odori e temperatura) di un oggetto, creatura o fenomeno fino a 6 m di lato, entro gittata; puoi spostarla con un\'azione magica e alterarne l\'aspetto in movimento. Non infligge danno né condizioni; l\'interazione fisica o una prova di Investigare contro la tua CD la smaschera. Con uno slot di 4°+ dura finché non viene dissolta, senza richiedere concentrazione.' },
    { id: 'evocare-non-morto', name: 'Evocare Non Morto', level: 3, school: 'Negromanzia',
      classes: ['warlock', 'mago'],
      meta: 'Azione · 27 m · 1 ora CONC · V, S, M (un teschio dorato, 300+ MO)',
      desc: 'Evochi uno spirito non morto (statistiche proprie) scegliendo la forma Spettrale, Putrida o Scheletrica: combatte al tuo fianco condividendo la tua iniziativa e obbedendo ai tuoi comandi.' },
    { id: 'lingue', name: 'Lingue', level: 3, school: 'Divinazione',
      classes: ['bardo', 'chierico', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · Tocco · 1 ora · V, M (uno ziggurat in miniatura)',
      desc: 'La creatura toccata comprende ogni lingua parlata o firmata che sente o vede per la durata; chiunque la ascolti comprende a sua volta ciò che dice o firma, purché conosca almeno una lingua.' },
    { id: 'tocco-vampirico', name: 'Tocco Vampirico', level: 3, school: 'Negromanzia',
      classes: ['stregone', 'warlock', 'mago'],
      meta: 'Azione · Sé · 1 min CONC · V, S',
      desc: 'Attacco con incantesimo in mischia: se colpisci, 3d6 necrotici e recuperi PF pari alla metà del danno inflitto. Nei turni successivi puoi ripetere l\'attacco (azione magica) contro lo stesso bersaglio o uno diverso. +1d6 per ogni slot oltre il 3°.' },

    { id: 'piaga', name: 'Piaga', level: 4, school: 'Negromanzia',
      classes: ['druido', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 9 m · Istantaneo · V, S',
      desc: 'Il bersaglio fa TS Costituzione (le creature Pianta falliscono automaticamente), subendo 8d8 necrotici (metà se supera). In alternativa puoi colpire una pianta non magica non senziente, che appassisce senza TS. +1d8 per ogni slot oltre il 4°.' },
    { id: 'ammaliare-mostro', name: 'Ammaliare Mostro', level: 4, school: 'Incantamento',
      classes: ['bardo', 'druido', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 9 m · 1 ora · V, S',
      desc: 'Una creatura fa TS Saggezza (con vantaggio se in combattimento con te) o è Affascinata finché dura o finché tu/alleati gli infliggete danno; nel frattempo ti è Amichevole e, quando l\'incantesimo termina, sa di essere stata Affascinata. +1 bersaglio per ogni slot oltre il 4°.' },
    { id: 'porta-dimensionale', name: 'Porta Dimensionale', level: 4, school: 'Convocazione',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 150 m · Istantaneo · V',
      desc: 'Ti teletrasporti in un punto entro gittata (visto, immaginato o descritto per distanza e direzione), portando con te anche una creatura volontaria entro 1,5 m. Se tu o l\'altra creatura arrivereste in uno spazio occupato, entrambi subite 4d6 forza e il teletrasporto fallisce.' },
    { id: 'terreno-illusorio', name: 'Terreno Illusorio', level: 4, school: 'Illusione',
      classes: ['bardo', 'druido', 'warlock', 'mago'],
      meta: '10 minuti · 90 m · 24 ore · V, S, M (un fungo)',
      desc: 'Un terreno naturale in un cubo di 45 m appare, suona e odora come un altro tipo di terreno (es. un campo sembra una palude). Strutture, equipaggiamento e creature non cambiano. Il tatto rivela l\'inganno; una prova di Investigare contro la tua CD (azione di Studio) lo smaschera a vista.' },
    { id: 'evocare-aberrazione', name: 'Evocare Aberrazione', level: 4, school: 'Convocazione',
      classes: ['warlock', 'mago'],
      meta: 'Azione · 27 m · 1 ora CONC · V, S, M (un tentacolo sottaceto e un occhio in una fiala rivestita di platino, 400+ MO)',
      desc: 'Evochi uno spirito aberrante (statistiche proprie) scegliendo Beholderkin, Divoratore di Menti o Slaad: combatte al tuo fianco condividendo la tua iniziativa e obbedendo ai tuoi comandi.' },

    { id: 'contattare-altro-piano', name: 'Contattare Altro Piano', level: 5, school: 'Divinazione',
      classes: ['warlock', 'mago'],
      meta: '1 minuto o Rituale · Sé · 1 minuto · V',
      desc: 'Contatti mentalmente un\'entità ultraterrena: fai un TS Intelligenza CD 15. Se superi, puoi porre fino a cinque domande a cui il Master risponde con una parola (o una breve frase se necessario). Se fallisci, subisci 6d6 psichici e sei Incapace di Agire fino al prossimo riposo lungo (curabile con Ristorare Superiore).' },
    { id: 'sogno', name: 'Sogno', level: 5, school: 'Illusione',
      classes: ['bardo', 'warlock', 'mago'],
      meta: '1 minuto · Speciale · 8 ore · V, S, M (una manciata di sabbia)',
      desc: 'Tu o un messaggero volontario toccato entrate in trance (Incapace di Agire, velocità 0) per contattare in sogno un bersaglio conosciuto sullo stesso piano, potendo conversare e plasmare l\'ambiente onirico finché dorme. Puoi rendere il messaggero terrificante: consegna un messaggio di massimo 10 parole, poi il bersaglio fa TS Saggezza o non trae beneficio dal riposo e subisce 3d6 psichici al risveglio.' },
    { id: 'paralizzare-mostro', name: 'Paralizzare Mostro', level: 5, school: 'Incantamento',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 27 m · 1 min CONC · V, S, M (un pezzo di ferro dritto)',
      desc: 'Una creatura fa TS Saggezza o è Paralizzata finché dura, ripetendo il TS a fine di ogni suo turno. +1 bersaglio per ogni slot oltre il 5°.' },
    { id: 'tempesta-di-radiosita-di-jallarzi', name: 'Tempesta di Radiosità di Jallarzi', level: 5, school: 'Evocazione',
      classes: ['warlock', 'mago'],
      meta: 'Azione · 36 m · 1 min CONC · V, S, M (un pizzico di fosforo)',
      desc: 'Una tempesta di luce e tuono riempie un Cilindro di 3 m di raggio e 12 m di altezza: chi vi si trova è Accecato e Assordato e non può lanciare incantesimi con componente Verbale. Alla comparsa (e quando una creatura vi entra o vi termina il turno) TS Costituzione, subendo 2d10 radiosi + 2d10 tuono (metà se supera, una volta a turno). +1d10 a ciascun danno per ogni slot oltre il 5°.' },
    { id: 'sviare', name: 'Sviare', level: 5, school: 'Illusione',
      classes: ['bardo', 'warlock', 'mago'],
      meta: 'Azione · Sé · 1 ora CONC · S',
      desc: 'Diventi Invisibile mentre un tuo doppio illusorio appare al tuo posto; l\'invisibilità termina subito se attacchi, infliggi danno o lanci un incantesimo. Con un\'azione magica muovi il doppio (intangibile e invulnerabile) fino al doppio della tua velocità, facendolo gesticolare e parlare, e puoi vedere e sentire attraverso di esso.' },
    { id: 'vincolo-planare', name: 'Vincolo Planare', level: 5, school: 'Abiurazione',
      classes: ['bardo', 'chierico', 'druido', 'warlock', 'mago'],
      meta: '1 ora · 18 m · 24 ore · V, S, M (un gioiello da 1.000+ MO, consumato)',
      desc: 'Tenti di vincolare un Celestiale, un Elementale, un Folletto o un Immondo al tuo servizio: al termine del lancio fa TS Carisma o è vincolato a obbedire ai tuoi comandi per la durata. Con slot di 6° dura 10 giorni, 7° trenta giorni, 8° centottanta giorni, 9° trecentosessantasei giorni.' },
    { id: 'scrutare', name: 'Scrutare', level: 5, school: 'Divinazione',
      classes: ['bardo', 'chierico', 'druido', 'warlock', 'mago'],
      meta: '10 minuti · Sé · 10 min CONC · V, S, M (un focus da 1.000+ MO: sfera di cristallo, specchio o fonte d\'acqua)',
      desc: 'Vedi e senti un bersaglio a scelta sullo stesso piano: fa un TS Saggezza modificato da quanto lo conosci e da un\'eventuale connessione fisica con esso (oggetto appartenuto, ciocca di capelli, ecc.); se fallisce, ottieni un sensore invisibile nei suoi pressi per la durata.' },
    { id: 'statica-sinaptica', name: 'Statica Sinaptica', level: 5, school: 'Incantamento',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 36 m · Istantaneo · V, S',
      desc: 'Energia psichica erompe in una sfera di 6 m di raggio: le creature fanno TS Intelligenza, subendo 8d6 psichici (metà se superano). Chi fallisce ha pensieri confusi per 1 minuto: −1d6 a tiri per colpire, prove e TS Costituzione per mantenere la concentrazione (ripete il TS a fine turno per liberarsi).' },
    { id: 'cerchio-di-teletrasporto', name: 'Cerchio di Teletrasporto', level: 5, school: 'Convocazione',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: '1 minuto · 3 m · 1 round · V, M (inchiostri rari da 50+ MO, consumati)',
      desc: 'Disegni un cerchio di 1,5 m di raggio che collega la tua posizione a un cerchio di teletrasporto permanente a te noto: per 1 round si apre un portale che chiunque può attraversare per raggiungere l\'altro cerchio.' },

    { id: 'portale-arcano', name: 'Portale Arcano', level: 6, school: 'Convocazione',
      classes: ['stregone', 'warlock', 'mago'],
      meta: 'Azione · 150 m · 10 min CONC · V, S',
      desc: 'Crei due portali circolari collegati (uno entro gittata, uno entro 3 m da te), aperti su un solo lato a tua scelta: ciò che entra da un lato esce dall\'altro come se fossero adiacenti. Azione bonus per cambiare il lato aperto.' },
    { id: 'cerchio-di-morte', name: 'Cerchio di Morte', level: 6, school: 'Negromanzia',
      classes: ['stregone', 'warlock', 'mago'],
      meta: 'Azione · 45 m · Istantaneo · V, S, M (polvere di perla nera, 500+ MO)',
      desc: 'Energia negativa si propaga in una sfera di 18 m di raggio: le creature fanno TS Costituzione, subendo 8d8 necrotici (metà se superano). +2d8 per ogni slot oltre il 6°.' },
    { id: 'creare-non-morti', name: 'Creare Non Morti', level: 6, school: 'Negromanzia',
      classes: ['chierico', 'warlock', 'mago'],
      meta: '1 minuto · 3 m · Istantaneo · V, S, M (una pietra d\'onice nera da 150+ MO per ogni cadavere)',
      desc: 'Lanciabile solo di notte: fino a tre cadaveri Umanoidi Medi o Piccoli entro gittata diventano Ghoul sotto il tuo controllo. Azione bonus per comandarli mentalmente (entro 36 m); restano sotto controllo per 24 ore, rinnovabili rilanciando l\'incantesimo prima della scadenza.' },
    { id: 'morso-dell-occhio', name: 'Morso dell\'Occhio', level: 6, school: 'Negromanzia',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · Sé · 1 min CONC · V, S',
      desc: 'I tuoi occhi diventano un vuoto nero: una creatura entro 18 m fa TS Saggezza o subisce uno tra tre effetti a scelta (Addormentato: Incosciente finché non subisce danno; Nel Panico: Spaventata, deve Scattare lontano da te; Malato: Avvelenato) finché dura. Azione magica nei turni successivi per bersagliare un\'altra creatura, purché non abbia già superato il TS contro questo lancio.' },
    { id: 'evocare-immondo', name: 'Evocare Immondo', level: 6, school: 'Convocazione',
      classes: ['warlock', 'mago'],
      meta: 'Azione · 27 m · 1 ora CONC · V, S, M (una fiala insanguinata, 600+ MO)',
      desc: 'Evochi uno spirito immondo (statistiche proprie) scegliendo Demone, Diavolo o Yugoloth: combatte al tuo fianco condividendo la tua iniziativa e obbedendo ai tuoi comandi.' },
    { id: 'calderone-ribollente-di-tasha', name: 'Calderone Ribollente di Tasha', level: 6, school: 'Convocazione',
      classes: ['warlock', 'mago'],
      meta: 'Azione · 1,5 m · 10 minuti · V, S, M (un mestolo dorato, 500+ MO)',
      desc: 'Convochi un calderone che duplica le proprietà di una pozione Comune o Non Comune a tua scelta: con un\'azione bonus tu o un alleato potete estrarne una pozione (fino a un numero pari al tuo modificatore da incantatore, minimo 1). Il calderone svanisce quando finiscono le pozioni o quando lanci di nuovo l\'incantesimo.' },
    { id: 'vista-vera', name: 'Vista Vera', level: 6, school: 'Divinazione',
      classes: ['bardo', 'chierico', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · Tocco · 1 ora · V, S, M (polvere di fungo, 25+ MO, consumata)',
      desc: 'La creatura volontaria toccata ottiene Vista Vera con raggio 36 m per la durata.' },

    { id: 'eterealita', name: 'Eterealità', level: 7, school: 'Convocazione',
      classes: ['bardo', 'chierico', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · Sé · fino a 8 ore · V, S',
      desc: 'Entri nelle regioni di confine del Piano Etereo, dove si sovrappone al tuo piano attuale. Puoi muoverti in ogni direzione (il movimento verticale costa il doppio), percepisci il piano lasciato (in grigio, fino a 18 m) e puoi interagire solo con creature e oggetti sul Piano Etereo. Termina istantaneamente se lo lanci mentre sei già sul Piano Etereo o su un piano che non vi confina. +3 bersagli volontari (entro 3 m) per ogni slot oltre il 7°.' },
    { id: 'dito-della-morte', name: 'Dito della Morte', level: 7, school: 'Negromanzia',
      classes: ['stregone', 'warlock', 'mago'],
      meta: 'Azione · 18 m · Istantaneo · V, S',
      desc: 'Il bersaglio fa TS Costituzione, subendo 7d8+30 necrotici (metà se supera). Un Umanoide ucciso da questo incantesimo risorge come uno Zombie ai tuoi ordini all\'inizio del tuo turno successivo.' },
    { id: 'gabbia-di-forza', name: 'Gabbia di Forza', level: 7, school: 'Evocazione',
      classes: ['bardo', 'warlock', 'mago'],
      meta: 'Azione · 30 m · 1 ora CONC · V, S, M (polvere di rubino, 1.500+ MO, consumata)',
      desc: 'Una prigione invisibile e immobile di forza magica (gabbia fino a 6 m di lato, o scatola solida fino a 3 m) imprigiona le creature interamente al suo interno. Per uscire con teletrasporto o viaggio interplanare serve un TS Carisma superato; altrimenti il tentativo fallisce e lo spreca. Non può essere dissolta con Dissolvi Magie.' },
    { id: 'spostamento-di-piano', name: 'Spostamento di Piano', level: 7, school: 'Convocazione',
      classes: ['chierico', 'druido', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · Tocco · Istantaneo · V, S, M (un\'asta di metallo forcuta, 250+ MO, sintonizzata su un piano)',
      desc: 'Tu e fino a otto creature volontarie che vi tenete per mano venite trasportati su un altro piano di esistenza, in una destinazione generale a tua scelta. In alternativa, se conosci la sequenza di un cerchio di teletrasporto su un altro piano, puoi raggiungerlo direttamente.' },

    { id: 'frastornare', name: 'Frastornare', level: 8, school: 'Incantamento',
      classes: ['bardo', 'druido', 'warlock', 'mago'],
      meta: 'Azione · 45 m · Istantaneo · V, S, M (un portachiavi senza chiavi)',
      desc: 'Colpisci la mente di un bersaglio, che fa TS Intelligenza. In combattimento deve poi superare un TS Saggezza a inizio di ogni suo turno o è costretto a Schivare; ogni volta che gli infliggi danno subisce +1d8 necrotico extra. Con slot di 4° dura 10 minuti in concentrazione; con 5°+ non richiede concentrazione (8 ore con slot 5°-6°, 24 ore con 7°-8°); con slot di 9° dura finché non viene dissolto.' },
    { id: 'semipiano', name: 'Semipiano', level: 8, school: 'Convocazione',
      classes: ['stregone', 'warlock', 'mago'],
      meta: 'Azione · 18 m · 1 ora · S',
      desc: 'Crei una porta ombrosa su una superficie solida che conduce a un semipiano vuoto di 9 m per lato (legno o pietra, a scelta). Quando l\'incantesimo termina, la porta svanisce; oggetti e creature dentro restano, a meno che scelgano di uscire mentre la porta scompare (atterrando Proni). Puoi ricollegare la porta a un semipiano creato in precedenza.' },
    { id: 'dominare-mostro', name: 'Dominare Mostro', level: 8, school: 'Incantamento',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 18 m · 1 ora CONC · V, S',
      desc: 'Una creatura fa TS Saggezza (con vantaggio se in combattimento con te) o è Affascinata per la durata; ripete il TS quando subisce danno. Hai un legame telepatico per impartirle comandi (nessuna azione richiesta); se non ne riceve, agisce proteggendosi. Con slot di 9° dura fino a 8 ore.' },
    { id: 'parlantina', name: 'Parlantina', level: 8, school: 'Incantamento',
      classes: ['bardo', 'warlock'],
      meta: 'Azione · Sé · 1 ora · V',
      desc: 'Finché dura, puoi sostituire il risultato di ogni prova di Carisma con un 15, e qualsiasi magia usata per verificare se menti indica che stai dicendo la verità.' },
    { id: 'parola-di-potere-stordire', name: 'Parola di Potere: Stordire', level: 8, school: 'Incantamento',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 18 m · Istantaneo · V',
      desc: 'Travolgi la mente di un bersaglio: se ha 150 PF o meno è Stordito, altrimenti la sua velocità diventa 0 fino al tuo prossimo turno. Il bersaglio Stordito ripete un TS Costituzione a fine di ogni suo turno per liberarsi.' },

    { id: 'proiezione-astrale', name: 'Proiezione Astrale', level: 9, school: 'Negromanzia',
      classes: ['chierico', 'warlock', 'mago'],
      meta: '1 ora · 3 m · Finché non dissolto · V, S, M (per ogni bersaglio: un giacinto da 7.000+ MO e una barra d\'argento da 100+ MO, consumati)',
      desc: 'Tu e fino a otto creature volontarie proiettate il corpo astrale sul Piano Astrale; i corpi restano in animazione sospesa (Incoscienti, senza bisogno di cibo o aria). Un cordone d\'argento collega corpo e forma astrale: se viene reciso, entrambi muoiono. Se il corpo o la forma astrale di un bersaglio scende a 0 PF, l\'incantesimo termina per lui.' },
    { id: 'preveggenza', name: 'Preveggenza', level: 9, school: 'Divinazione',
      classes: ['bardo', 'druido', 'warlock', 'mago'],
      meta: '1 minuto · Tocco · 8 ore · V, S, M (una piuma di colibrì)',
      desc: 'La creatura volontaria toccata ottiene vantaggio a tutti i D20 Test per la durata, e le creature nemiche hanno svantaggio ad attaccarla. Termina prima se lo lanci di nuovo.' },
    { id: 'cancello', name: 'Cancello', level: 9, school: 'Convocazione',
      classes: ['chierico', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 18 m · 1 min CONC · V, S, M (un diamante da 5.000+ MO)',
      desc: 'Convochi un portale circolare (3-6 m di diametro) che collega uno spazio libero entro gittata a un luogo preciso di un altro piano, visibile attraverso di esso. Il portale ha un fronte e un retro: attraversarlo dal fronte trasporta istantaneamente sull\'altro piano, nello spazio libero più vicino.' },
    { id: 'imprigionamento', name: 'Imprigionamento', level: 9, school: 'Abiurazione',
      classes: ['warlock', 'mago'],
      meta: '1 minuto · 9 m · Finché non dissolto · V, S, M (una statuetta del bersaglio, 5.000+ MO)',
      desc: 'Crei un vincolo magico per trattenere una creatura: fa TS Saggezza o è imprigionata (non deve respirare, mangiare né bere, e non invecchia; non individuabile con divinazioni né in grado di teletrasportarsi). Se supera, è immune per 24 ore. Scegli anche uno tra più effetti aggiuntivi (sepoltura in una sfera di forza, incatenamento al suolo, o un semipiano-prigione).' },
    { id: 'parola-di-potere-uccidere', name: 'Parola di Potere: Uccidere', level: 9, school: 'Incantamento',
      classes: ['bardo', 'stregone', 'warlock', 'mago'],
      meta: 'Azione · 18 m · Istantaneo · V',
      desc: 'Costringi una creatura vista entro gittata a morire: se ha 100 PF o meno, muore all\'istante. Altrimenti subisce 12d12 psichici.' },
    { id: 'vera-metamorfosi', name: 'Vera Metamorfosi', level: 9, school: 'Trasmutazione',
      classes: ['bardo', 'warlock', 'mago'],
      meta: 'Azione · 9 m · 1 ora CONC · V, S, M (una goccia di mercurio, gomma arabica e un filo di fumo)',
      desc: 'Una creatura o un oggetto non magico entro gittata si trasforma in un\'altra creatura o in un oggetto non magico (l\'oggetto trasformato non deve essere indossato né trasportato). La trasformazione dura finché mantieni la concentrazione per l\'intera durata, dopodiché diventa permanente.' },
    { id: 'orrore-illusorio', name: 'Orrore Illusorio', level: 9, school: 'Illusione',
      classes: ['warlock', 'mago'],
      meta: 'Azione · 36 m · 1 min CONC · V, S',
      desc: 'Crei terrori illusori nella mente altrui: le creature scelte in una sfera di 9 m fanno TS Saggezza, subendo 10d10 psichici e diventando Spaventate per la durata (metà danno se superano). Chi resta Spaventato ripete il TS a fine turno, subendo 5d10 psichici se fallisce o liberandosi se supera.' }
  ]
};
